<?php
return [
    'service_manager' => [
        'aliases' => [
            \Facturacion\Repository\ITtagenRepository::class => \Facturacion\Repository\Impl\TtagenRepository::class,
            \Facturacion\Repository\ITtautoRepository::class => \Facturacion\Repository\Impl\TtautoRepository::class,
            \Facturacion\Repository\ITtchccRepository::class => \Facturacion\Repository\Impl\TtchccRepository::class,
            \Facturacion\Repository\ITtcidiRepository::class => \Facturacion\Repository\Impl\TtcidiRepository::class,
            \Facturacion\Repository\ITtcpagRepository::class => \Facturacion\Repository\Impl\TtcpagRepository::class,
            \Facturacion\Repository\ITtdescRepository::class => \Facturacion\Repository\Impl\TtdescRepository::class,
            \Facturacion\Repository\ITtdistRepository::class => \Facturacion\Repository\Impl\TtdistRepository::class,
            \Facturacion\Repository\ITtdpdbRepository::class => \Facturacion\Repository\Impl\TtdpdbRepository::class,
            \Facturacion\Repository\ITtdscdRepository::class => \Facturacion\Repository\Impl\TtdscdRepository::class,
            \Facturacion\Repository\ITtdschRepository::class => \Facturacion\Repository\Impl\TtdschRepository::class,
            \Facturacion\Repository\ITtfpdiRepository::class => \Facturacion\Repository\Impl\TtfpdiRepository::class,
            \Facturacion\Repository\ITtfvadRepository::class => \Facturacion\Repository\Impl\TtfvadRepository::class,
            \Facturacion\Repository\ITtfvahRepository::class => \Facturacion\Repository\Impl\TtfvahRepository::class,
            \Facturacion\Repository\ITthvtmRepository::class => \Facturacion\Repository\Impl\TthvtmRepository::class,
             \Facturacion\Repository\ITtlprdRepository::class => \Facturacion\Repository\Impl\TtlprdRepository::class,
            \Facturacion\Repository\ITtlprhRepository::class => \Facturacion\Repository\Impl\TtlprhRepository::class,
            \Facturacion\Repository\ITtmoauRepository::class => \Facturacion\Repository\Impl\TtmoauRepository::class,
            \Facturacion\Repository\ITthzonRepository::class => \Facturacion\Repository\Impl\TthzonRepository::class,
            \Facturacion\Repository\ITtmovcRepository::class => \Facturacion\Repository\Impl\TtmovcRepository::class,
            \Facturacion\Repository\ITtncddRepository::class => \Facturacion\Repository\Impl\TtncddRepository::class,
            \Facturacion\Repository\ITtncdhRepository::class => \Facturacion\Repository\Impl\TtncdhRepository::class,
            \Facturacion\Repository\ITtncydRepository::class => \Facturacion\Repository\Impl\TtncydRepository::class,
            \Facturacion\Repository\ITtpeddRepository::class => \Facturacion\Repository\Impl\TtpeddRepository::class,
            \Facturacion\Repository\ITtpedhRepository::class => \Facturacion\Repository\Impl\TtpedhRepository::class,
            \Facturacion\Repository\ITtptovRepository::class => \Facturacion\Repository\Impl\TtptovRepository::class,
            \Facturacion\Repository\ITtpuemRepository::class => \Facturacion\Repository\Impl\TtpuemRepository::class,
            \Facturacion\Repository\ITtrvtdRepository::class => \Facturacion\Repository\Impl\TtrvtdRepository::class,
            \Facturacion\Repository\ITtrvthRepository::class => \Facturacion\Repository\Impl\TtrvthRepository::class,
            \Facturacion\Repository\ITttidoRepository::class => \Facturacion\Repository\Impl\TttidoRepository::class,
        ],
        'factories' => [
            \Facturacion\Repository\Impl\TtagenRepository::class => \Facturacion\Repository\Factory\TtagenRepositoryFactory::class,
            \Facturacion\Repository\Impl\TtautoRepository::class => \Facturacion\Repository\Factory\TtautoRepositoryFactory::class,
            \Facturacion\Repository\Impl\TtchccRepository::class => \Facturacion\Repository\Factory\TtchccRepositoryFactory::class,
            \Facturacion\Repository\Impl\TtcidiRepository::class => \Facturacion\Repository\Factory\TtcidiRepositoryFactory::class,
            \Facturacion\Repository\Impl\TtcpagRepository::class => \Facturacion\Repository\Factory\TtcpagRepositoryFactory::class,
            \Facturacion\Repository\Impl\TtdescRepository::class => \Facturacion\Repository\Factory\TtdescRepositoryFactory::class,
            \Facturacion\Repository\Impl\TtdistRepository::class => \Facturacion\Repository\Factory\TtdistRepositoryFactory::class,
            \Facturacion\Repository\Impl\TtdpdbRepository::class => \Facturacion\Repository\Factory\TtdpdbRepositoryFactory::class,
            \Facturacion\Repository\Impl\TtdscdRepository::class => \Facturacion\Repository\Factory\TtdscdRepositoryFactory::class,
            \Facturacion\Repository\Impl\TtdschRepository::class => \Facturacion\Repository\Factory\TtdschRepositoryFactory::class,
            \Facturacion\Repository\Impl\TtfpdiRepository::class => \Facturacion\Repository\Factory\TtfpdiRepositoryFactory::class,
            \Facturacion\Repository\Impl\TtfvadRepository::class => \Facturacion\Repository\Factory\TtfvadRepositoryFactory::class,
             \Facturacion\Repository\Impl\TtfvahRepository::class => \Facturacion\Repository\Factory\TtfvahRepositoryFactory::class,
            \Facturacion\Repository\Impl\TthvtmRepository::class => \Facturacion\Repository\Factory\TthvtmRepositoryFactory::class,
            \Facturacion\Repository\Impl\TtlprdRepository::class => \Facturacion\Repository\Factory\TtlprdRepositoryFactory::class,
            \Facturacion\Repository\Impl\TtlprhRepository::class => \Facturacion\Repository\Factory\TtlprhRepositoryFactory::class,
            \Facturacion\Repository\Impl\TtmoauRepository::class => \Facturacion\Repository\Factory\TtmoauRepositoryFactory::class,
            \Facturacion\Repository\Impl\TthzonRepository::class => \Facturacion\Repository\Factory\TthzonRepositoryFactory::class,
            \Facturacion\Repository\Impl\TtmovcRepository::class => \Facturacion\Repository\Factory\TtmovcRepositoryFactory::class,
            \Facturacion\Repository\Impl\TtncddRepository::class => \Facturacion\Repository\Factory\TtncddRepositoryFactory::class,
            \Facturacion\Repository\Impl\TtncdhRepository::class => \Facturacion\Repository\Factory\TtncdhRepositoryFactory::class,
            \Facturacion\Repository\Impl\TtncydRepository::class => \Facturacion\Repository\Factory\TtncydRepositoryFactory::class,
            \Facturacion\Repository\Impl\TtpeddRepository::class => \Facturacion\Repository\Factory\TtpeddRepositoryFactory::class,
            \Facturacion\Repository\Impl\TtpedhRepository::class => \Facturacion\Repository\Factory\TtpedhRepositoryFactory::class,
            \Facturacion\Repository\Impl\TtptovRepository::class => \Facturacion\Repository\Factory\TtptovRepositoryFactory::class,
            \Facturacion\Repository\Impl\TtpuemRepository::class => \Facturacion\Repository\Factory\TtpuemRepositoryFactory::class,
            \Facturacion\Repository\Impl\TtrvtdRepository::class => \Facturacion\Repository\Factory\TtrvtdRepositoryFactory::class,
            \Facturacion\Repository\Impl\TtrvthRepository::class => \Facturacion\Repository\Factory\TtrvthRepositoryFactory::class,
            \Facturacion\Repository\Impl\TttidoRepository::class => \Facturacion\Repository\Factory\TttidoRepositoryFactory::class,
            //Resource
            \Facturacion\V1\Rest\Ttagen\TtagenResource::class => \Facturacion\V1\Rest\Ttagen\TtagenResourceFactory::class,
            \Facturacion\V1\Rest\Ttauto\TtautoResource::class => \Facturacion\V1\Rest\Ttauto\TtautoResourceFactory::class,
            \Facturacion\V1\Rest\Ttchcc\TtchccResource::class => \Facturacion\V1\Rest\Ttchcc\TtchccResourceFactory::class,
            \Facturacion\V1\Rest\Ttcidi\TtcidiResource::class => \Facturacion\V1\Rest\Ttcidi\TtcidiResourceFactory::class,
            \Facturacion\V1\Rest\Ttcpag\TtcpagResource::class => \Facturacion\V1\Rest\Ttcpag\TtcpagResourceFactory::class,
            \Facturacion\V1\Rest\Ttdesc\TtdescResource::class => \Facturacion\V1\Rest\Ttdesc\TtdescResourceFactory::class,
            \Facturacion\V1\Rest\Ttdist\TtdistResource::class => \Facturacion\V1\Rest\Ttdist\TtdistResourceFactory::class,
            \Facturacion\V1\Rest\Ttdpdb\TtdpdbResource::class => \Facturacion\V1\Rest\Ttdpdb\TtdpdbResourceFactory::class,
            \Facturacion\V1\Rest\Ttdscd\TtdscdResource::class => \Facturacion\V1\Rest\Ttdscd\TtdscdResourceFactory::class,
            \Facturacion\V1\Rest\Ttdsch\TtdschResource::class => \Facturacion\V1\Rest\Ttdsch\TtdschResourceFactory::class,
            \Facturacion\V1\Rest\Ttfpdi\TtfpdiResource::class => \Facturacion\V1\Rest\Ttfpdi\TtfpdiResourceFactory::class,
            \Facturacion\V1\Rest\Ttfvad\TtfvadResource::class => \Facturacion\V1\Rest\Ttfvad\TtfvadResourceFactory::class,
            \Facturacion\V1\Rest\Ttfvah\TtfvahResource::class => \Facturacion\V1\Rest\Ttfvah\TtfvahResourceFactory::class,
            \Facturacion\V1\Rest\Tthvtm\TthvtmResource::class => \Facturacion\V1\Rest\Tthvtm\TthvtmResourceFactory::class,
            \Facturacion\V1\Rest\Ttlprd\TtlprdResource::class => \Facturacion\V1\Rest\Ttlprd\TtlprdResourceFactory::class,
            \Facturacion\V1\Rest\Ttlprh\TtlprhResource::class => \Facturacion\V1\Rest\Ttlprh\TtlprhResourceFactory::class,
            \Facturacion\V1\Rest\Ttmoau\TtmoauResource::class => \Facturacion\V1\Rest\Ttmoau\TtmoauResourceFactory::class,
            \Facturacion\V1\Rest\Tthzon\TthzonResource::class => \Facturacion\V1\Rest\Tthzon\TthzonResourceFactory::class,
            \Facturacion\V1\Rest\Ttmovc\TtmovcResource::class => \Facturacion\V1\Rest\Ttmovc\TtmovcResourceFactory::class,
            \Facturacion\V1\Rest\Ttncdd\TtncddResource::class => \Facturacion\V1\Rest\Ttncdd\TtncddResourceFactory::class,
            \Facturacion\V1\Rest\Ttncdh\TtncdhResource::class => \Facturacion\V1\Rest\Ttncdh\TtncdhResourceFactory::class,
            \Facturacion\V1\Rest\Ttncyd\TtncydResource::class => \Facturacion\V1\Rest\Ttncyd\TtncydResourceFactory::class,
            \Facturacion\V1\Rest\Ttpedd\TtpeddResource::class => \Facturacion\V1\Rest\Ttpedd\TtpeddResourceFactory::class,
            \Facturacion\V1\Rest\Ttpedh\TtpedhResource::class => \Facturacion\V1\Rest\Ttpedh\TtpedhResourceFactory::class,
            \Facturacion\V1\Rest\Ttptov\TtptovResource::class => \Facturacion\V1\Rest\Ttptov\TtptovResourceFactory::class,
            \Facturacion\V1\Rest\Ttpuem\TtpuemResource::class => \Facturacion\V1\Rest\Ttpuem\TtpuemResourceFactory::class,
            \Facturacion\V1\Rest\Ttrvtd\TtrvtdResource::class => \Facturacion\V1\Rest\Ttrvtd\TtrvtdResourceFactory::class,
            \Facturacion\V1\Rest\Ttrvth\TtrvthResource::class => \Facturacion\V1\Rest\Ttrvth\TtrvthResourceFactory::class,
            \Facturacion\V1\Rest\Tttido\TttidoResource::class => \Facturacion\V1\Rest\Tttido\TttidoResourceFactory::class,
        ],
    ],
    'router' => [
        'routes' => [
            'facturacion.rest.ttagen' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/ttagen[/:ttagen_id]',
                    'defaults' => [
                        'controller' => 'Facturacion\\V1\\Rest\\Ttagen\\Controller',
                    ],
                ],
            ],
            'facturacion.rest.ttauto' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/ttauto[/:ttauto_id]',
                    'defaults' => [
                        'controller' => 'Facturacion\\V1\\Rest\\Ttauto\\Controller',
                    ],
                ],
            ],
            'facturacion.rest.ttchcc' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/ttchcc[/:ttchcc_id]',
                    'defaults' => [
                        'controller' => 'Facturacion\\V1\\Rest\\Ttchcc\\Controller',
                    ],
                ],
            ],
            'facturacion.rest.ttcidi' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/ttcidi[/:ttcidi_id]',
                    'defaults' => [
                        'controller' => 'Facturacion\\V1\\Rest\\Ttcidi\\Controller',
                    ],
                ],
            ],
            'facturacion.rest.ttcpag' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/ttcpag[/:ttcpag_id]',
                    'defaults' => [
                        'controller' => 'Facturacion\\V1\\Rest\\Ttcpag\\Controller',
                    ],
                ],
            ],
            'facturacion.rest.ttdesc' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/ttdesc[/:ttdesc_id]',
                    'defaults' => [
                        'controller' => 'Facturacion\\V1\\Rest\\Ttdesc\\Controller',
                    ],
                ],
            ],
            'facturacion.rest.ttdist' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/ttdist[/:ttdist_id]',
                    'defaults' => [
                        'controller' => 'Facturacion\\V1\\Rest\\Ttdist\\Controller',
                    ],
                ],
            ],
            'facturacion.rest.ttdpdb' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/ttdpdb[/:ttdpdb_id]',
                    'defaults' => [
                        'controller' => 'Facturacion\\V1\\Rest\\Ttdpdb\\Controller',
                    ],
                ],
            ],
            'facturacion.rest.ttdscd' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/ttdscd[/:ttdscd_id]',
                    'defaults' => [
                        'controller' => 'Facturacion\\V1\\Rest\\Ttdscd\\Controller',
                    ],
                ],
            ],
            'facturacion.rest.ttdsch' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/ttdsch[/:ttdsch_id]',
                    'defaults' => [
                        'controller' => 'Facturacion\\V1\\Rest\\Ttdsch\\Controller',
                    ],
                ],
            ],
            'facturacion.rest.ttfpdi' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/ttfpdi[/:ttfpdi_id]',
                    'defaults' => [
                        'controller' => 'Facturacion\\V1\\Rest\\Ttfpdi\\Controller',
                    ],
                ],
            ],
            'facturacion.rest.ttfvad' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/ttfvad[/:ttfvad_id]',
                    'defaults' => [
                        'controller' => 'Facturacion\\V1\\Rest\\Ttfvad\\Controller',
                    ],
                ],
            ],
            'facturacion.rest.ttfvah' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/ttfvah[/:ttfvah_id]',
                    'defaults' => [
                        'controller' => 'Facturacion\\V1\\Rest\\Ttfvah\\Controller',
                    ],
                ],
            ],
            'facturacion.rest.tthvtm' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tthvtm[/:tthvtm_id]',
                    'defaults' => [
                        'controller' => 'Facturacion\\V1\\Rest\\Tthvtm\\Controller',
                    ],
                ],
            ],
            'facturacion.rest.ttlprd' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/ttlprd[/:ttlprd_id]',
                    'defaults' => [
                        'controller' => 'Facturacion\\V1\\Rest\\Ttlprd\\Controller',
                    ],
                ],
            ],
            'facturacion.rest.ttlprh' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/ttlprh[/:ttlprh_id]',
                    'defaults' => [
                        'controller' => 'Facturacion\\V1\\Rest\\Ttlprh\\Controller',
                    ],
                ],
            ],
            'facturacion.rest.ttmoau' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/ttmoau[/:ttmoau_id]',
                    'defaults' => [
                        'controller' => 'Facturacion\\V1\\Rest\\Ttmoau\\Controller',
                    ],
                ],
            ],
            'facturacion.rest.tthzon' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tthzon[/:tthzon_id]',
                    'defaults' => [
                        'controller' => 'Facturacion\\V1\\Rest\\Tthzon\\Controller',
                    ],
                ],
            ],
            'facturacion.rest.ttmovc' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/ttmovc[/:ttmovc_id]',
                    'defaults' => [
                        'controller' => 'Facturacion\\V1\\Rest\\Ttmovc\\Controller',
                    ],
                ],
            ],
            'facturacion.rest.ttncdd' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/ttncdd[/:ttncdd_id]',
                    'defaults' => [
                        'controller' => 'Facturacion\\V1\\Rest\\Ttncdd\\Controller',
                    ],
                ],
            ],
            'facturacion.rest.ttncdh' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/ttncdh[/:ttncdh_id]',
                    'defaults' => [
                        'controller' => 'Facturacion\\V1\\Rest\\Ttncdh\\Controller',
                    ],
                ],
            ],
            'facturacion.rest.ttncyd' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/ttncyd[/:ttncyd_id]',
                    'defaults' => [
                        'controller' => 'Facturacion\\V1\\Rest\\Ttncyd\\Controller',
                    ],
                ],
            ],
            'facturacion.rest.ttpedd' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/ttpedd[/:ttpedd_id]',
                    'defaults' => [
                        'controller' => 'Facturacion\\V1\\Rest\\Ttpedd\\Controller',
                    ],
                ],
            ],
            'facturacion.rest.ttpedh' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/ttpedh[/:ttpedh_id]',
                    'defaults' => [
                        'controller' => 'Facturacion\\V1\\Rest\\Ttpedh\\Controller',
                    ],
                ],
            ],
            'facturacion.rest.ttptov' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/ttptov[/:ttptov_id]',
                    'defaults' => [
                        'controller' => 'Facturacion\\V1\\Rest\\Ttptov\\Controller',
                    ],
                ],
            ],
            'facturacion.rest.ttpuem' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/ttpuem[/:ttpuem_id]',
                    'defaults' => [
                        'controller' => 'Facturacion\\V1\\Rest\\Ttpuem\\Controller',
                    ],
                ],
            ],
            'facturacion.rest.ttrvtd' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/ttrvtd[/:ttrvtd_id]',
                    'defaults' => [
                        'controller' => 'Facturacion\\V1\\Rest\\Ttrvtd\\Controller',
                    ],
                ],
            ],
            'facturacion.rest.ttrvth' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/ttrvth[/:ttrvth_id]',
                    'defaults' => [
                        'controller' => 'Facturacion\\V1\\Rest\\Ttrvth\\Controller',
                    ],
                ],
            ],
            'facturacion.rest.tttido' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tttido[/:tttido_id]',
                    'defaults' => [
                        'controller' => 'Facturacion\\V1\\Rest\\Tttido\\Controller',
                    ],
                ],
            ],
        ],
    ],
    'zf-versioning' => [
        'uri' => [
            0 => 'facturacion.rest.ttagen',
            1 => 'facturacion.rest.ttauto',
            2 => 'facturacion.rest.ttchcc',
            3 => 'facturacion.rest.ttcidi',
            4 => 'facturacion.rest.ttcpag',
            5 => 'facturacion.rest.ttdesc',
            6 => 'facturacion.rest.ttdist',
            7 => 'facturacion.rest.ttdpdb',
            8 => 'facturacion.rest.ttdscd',
            9 => 'facturacion.rest.ttdsch',
            10 => 'facturacion.rest.ttfpdi',
            11 => 'facturacion.rest.ttfvad',
            12 => 'facturacion.rest.ttfvah',
            13 => 'facturacion.rest.tthvtm',
            15 => 'facturacion.rest.ttlprd',
            16 => 'facturacion.rest.ttlprh',
            17 => 'facturacion.rest.ttmoau',
            18 => 'facturacion.rest.tthzon',
            19 => 'facturacion.rest.ttmovc',
            20 => 'facturacion.rest.ttncdd',
            21 => 'facturacion.rest.ttncdh',
            22 => 'facturacion.rest.ttncyd',
            23 => 'facturacion.rest.ttpedd',
            24 => 'facturacion.rest.ttpedh',
            25 => 'facturacion.rest.ttptov',
            26 => 'facturacion.rest.ttpuem',
            27 => 'facturacion.rest.ttrvtd',
            28 => 'facturacion.rest.ttrvth',
            29 => 'facturacion.rest.tttido',
        ],
    ],
    'zf-rest' => [
        'Facturacion\\V1\\Rest\\Ttagen\\Controller' => [
            'listener' => \Facturacion\V1\Rest\Ttagen\TtagenResource::class,
            'route_name' => 'facturacion.rest.ttagen',
            'route_identifier_name' => 'ttagen_id',
            'collection_name' => 'ttagen',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Facturacion\V1\Rest\Ttagen\TtagenEntity::class,
            'collection_class' => \Facturacion\V1\Rest\Ttagen\TtagenCollection::class,
            'service_name' => 'Ttagen',
        ],
        'Facturacion\\V1\\Rest\\Ttauto\\Controller' => [
            'listener' => \Facturacion\V1\Rest\Ttauto\TtautoResource::class,
            'route_name' => 'facturacion.rest.ttauto',
            'route_identifier_name' => 'ttauto_id',
            'collection_name' => 'ttauto',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Facturacion\V1\Rest\Ttauto\TtautoEntity::class,
            'collection_class' => \Facturacion\V1\Rest\Ttauto\TtautoCollection::class,
            'service_name' => 'Ttauto',
        ],
        'Facturacion\\V1\\Rest\\Ttchcc\\Controller' => [
            'listener' => \Facturacion\V1\Rest\Ttchcc\TtchccResource::class,
            'route_name' => 'facturacion.rest.ttchcc',
            'route_identifier_name' => 'ttchcc_id',
            'collection_name' => 'ttchcc',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Facturacion\V1\Rest\Ttchcc\TtchccEntity::class,
            'collection_class' => \Facturacion\V1\Rest\Ttchcc\TtchccCollection::class,
            'service_name' => 'Ttchcc',
        ],
        'Facturacion\\V1\\Rest\\Ttcidi\\Controller' => [
            'listener' => \Facturacion\V1\Rest\Ttcidi\TtcidiResource::class,
            'route_name' => 'facturacion.rest.ttcidi',
            'route_identifier_name' => 'ttcidi_id',
            'collection_name' => 'ttcidi',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Facturacion\V1\Rest\Ttcidi\TtcidiEntity::class,
            'collection_class' => \Facturacion\V1\Rest\Ttcidi\TtcidiCollection::class,
            'service_name' => 'Ttcidi',
        ],
        'Facturacion\\V1\\Rest\\Ttcpag\\Controller' => [
            'listener' => \Facturacion\V1\Rest\Ttcpag\TtcpagResource::class,
            'route_name' => 'facturacion.rest.ttcpag',
            'route_identifier_name' => 'ttcpag_id',
            'collection_name' => 'ttcpag',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Facturacion\V1\Rest\Ttcpag\TtcpagEntity::class,
            'collection_class' => \Facturacion\V1\Rest\Ttcpag\TtcpagCollection::class,
            'service_name' => 'Ttcpag',
        ],
        'Facturacion\\V1\\Rest\\Ttdesc\\Controller' => [
            'listener' => \Facturacion\V1\Rest\Ttdesc\TtdescResource::class,
            'route_name' => 'facturacion.rest.ttdesc',
            'route_identifier_name' => 'ttdesc_id',
            'collection_name' => 'ttdesc',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Facturacion\V1\Rest\Ttdesc\TtdescEntity::class,
            'collection_class' => \Facturacion\V1\Rest\Ttdesc\TtdescCollection::class,
            'service_name' => 'Ttdesc',
        ],
        'Facturacion\\V1\\Rest\\Ttdist\\Controller' => [
            'listener' => \Facturacion\V1\Rest\Ttdist\TtdistResource::class,
            'route_name' => 'facturacion.rest.ttdist',
            'route_identifier_name' => 'ttdist_id',
            'collection_name' => 'ttdist',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Facturacion\V1\Rest\Ttdist\TtdistEntity::class,
            'collection_class' => \Facturacion\V1\Rest\Ttdist\TtdistCollection::class,
            'service_name' => 'Ttdist',
        ],
        'Facturacion\\V1\\Rest\\Ttdpdb\\Controller' => [
            'listener' => \Facturacion\V1\Rest\Ttdpdb\TtdpdbResource::class,
            'route_name' => 'facturacion.rest.ttdpdb',
            'route_identifier_name' => 'ttdpdb_id',
            'collection_name' => 'ttdpdb',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Facturacion\V1\Rest\Ttdpdb\TtdpdbEntity::class,
            'collection_class' => \Facturacion\V1\Rest\Ttdpdb\TtdpdbCollection::class,
            'service_name' => 'Ttdpdb',
        ],
        'Facturacion\\V1\\Rest\\Ttdscd\\Controller' => [
            'listener' => \Facturacion\V1\Rest\Ttdscd\TtdscdResource::class,
            'route_name' => 'facturacion.rest.ttdscd',
            'route_identifier_name' => 'ttdscd_id',
            'collection_name' => 'ttdscd',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Facturacion\V1\Rest\Ttdscd\TtdscdEntity::class,
            'collection_class' => \Facturacion\V1\Rest\Ttdscd\TtdscdCollection::class,
            'service_name' => 'Ttdscd',
        ],
        'Facturacion\\V1\\Rest\\Ttdsch\\Controller' => [
            'listener' => \Facturacion\V1\Rest\Ttdsch\TtdschResource::class,
            'route_name' => 'facturacion.rest.ttdsch',
            'route_identifier_name' => 'ttdsch_id',
            'collection_name' => 'ttdsch',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Facturacion\V1\Rest\Ttdsch\TtdschEntity::class,
            'collection_class' => \Facturacion\V1\Rest\Ttdsch\TtdschCollection::class,
            'service_name' => 'Ttdsch',
        ],
        'Facturacion\\V1\\Rest\\Ttfpdi\\Controller' => [
            'listener' => \Facturacion\V1\Rest\Ttfpdi\TtfpdiResource::class,
            'route_name' => 'facturacion.rest.ttfpdi',
            'route_identifier_name' => 'ttfpdi_id',
            'collection_name' => 'ttfpdi',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Facturacion\V1\Rest\Ttfpdi\TtfpdiEntity::class,
            'collection_class' => \Facturacion\V1\Rest\Ttfpdi\TtfpdiCollection::class,
            'service_name' => 'Ttfpdi',
        ],
        'Facturacion\\V1\\Rest\\Ttfvad\\Controller' => [
            'listener' => \Facturacion\V1\Rest\Ttfvad\TtfvadResource::class,
            'route_name' => 'facturacion.rest.ttfvad',
            'route_identifier_name' => 'ttfvad_id',
            'collection_name' => 'ttfvad',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Facturacion\V1\Rest\Ttfvad\TtfvadEntity::class,
            'collection_class' => \Facturacion\V1\Rest\Ttfvad\TtfvadCollection::class,
            'service_name' => 'Ttfvad',
        ],
        'Facturacion\\V1\\Rest\\Ttfvah\\Controller' => [
            'listener' => \Facturacion\V1\Rest\Ttfvah\TtfvahResource::class,
            'route_name' => 'facturacion.rest.ttfvah',
            'route_identifier_name' => 'ttfvah_id',
            'collection_name' => 'ttfvah',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Facturacion\V1\Rest\Ttfvah\TtfvahEntity::class,
            'collection_class' => \Facturacion\V1\Rest\Ttfvah\TtfvahCollection::class,
            'service_name' => 'Ttfvah',
        ],
        'Facturacion\\V1\\Rest\\Tthvtm\\Controller' => [
            'listener' => \Facturacion\V1\Rest\Tthvtm\TthvtmResource::class,
            'route_name' => 'facturacion.rest.tthvtm',
            'route_identifier_name' => 'tthvtm_id',
            'collection_name' => 'tthvtm',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Facturacion\V1\Rest\Tthvtm\TthvtmEntity::class,
            'collection_class' => \Facturacion\V1\Rest\Tthvtm\TthvtmCollection::class,
            'service_name' => 'Tthvtm',
        ],
        'Facturacion\\V1\\Rest\\Ttlprd\\Controller' => [
            'listener' => \Facturacion\V1\Rest\Ttlprd\TtlprdResource::class,
            'route_name' => 'facturacion.rest.ttlprd',
            'route_identifier_name' => 'ttlprd_id',
            'collection_name' => 'ttlprd',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Facturacion\V1\Rest\Ttlprd\TtlprdEntity::class,
            'collection_class' => \Facturacion\V1\Rest\Ttlprd\TtlprdCollection::class,
            'service_name' => 'Ttlprd',
        ],
        'Facturacion\\V1\\Rest\\Ttlprh\\Controller' => [
            'listener' => \Facturacion\V1\Rest\Ttlprh\TtlprhResource::class,
            'route_name' => 'facturacion.rest.ttlprh',
            'route_identifier_name' => 'ttlprh_id',
            'collection_name' => 'ttlprh',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Facturacion\V1\Rest\Ttlprh\TtlprhEntity::class,
            'collection_class' => \Facturacion\V1\Rest\Ttlprh\TtlprhCollection::class,
            'service_name' => 'Ttlprh',
        ],
        'Facturacion\\V1\\Rest\\Ttmoau\\Controller' => [
            'listener' => \Facturacion\V1\Rest\Ttmoau\TtmoauResource::class,
            'route_name' => 'facturacion.rest.ttmoau',
            'route_identifier_name' => 'ttmoau_id',
            'collection_name' => 'ttmoau',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Facturacion\V1\Rest\Ttmoau\TtmoauEntity::class,
            'collection_class' => \Facturacion\V1\Rest\Ttmoau\TtmoauCollection::class,
            'service_name' => 'Ttmoau',
        ],
        'Facturacion\\V1\\Rest\\Tthzon\\Controller' => [
            'listener' => \Facturacion\V1\Rest\Tthzon\TthzonResource::class,
            'route_name' => 'facturacion.rest.tthzon',
            'route_identifier_name' => 'tthzon_id',
            'collection_name' => 'tthzon',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Facturacion\V1\Rest\Tthzon\TthzonEntity::class,
            'collection_class' => \Facturacion\V1\Rest\Tthzon\TthzonCollection::class,
            'service_name' => 'Tthzon',
        ],
        'Facturacion\\V1\\Rest\\Ttmovc\\Controller' => [
            'listener' => \Facturacion\V1\Rest\Ttmovc\TtmovcResource::class,
            'route_name' => 'facturacion.rest.ttmovc',
            'route_identifier_name' => 'ttmovc_id',
            'collection_name' => 'ttmovc',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Facturacion\V1\Rest\Ttmovc\TtmovcEntity::class,
            'collection_class' => \Facturacion\V1\Rest\Ttmovc\TtmovcCollection::class,
            'service_name' => 'Ttmovc',
        ],
        'Facturacion\\V1\\Rest\\Ttncdd\\Controller' => [
            'listener' => \Facturacion\V1\Rest\Ttncdd\TtncddResource::class,
            'route_name' => 'facturacion.rest.ttncdd',
            'route_identifier_name' => 'ttncdd_id',
            'collection_name' => 'ttncdd',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Facturacion\V1\Rest\Ttncdd\TtncddEntity::class,
            'collection_class' => \Facturacion\V1\Rest\Ttncdd\TtncddCollection::class,
            'service_name' => 'Ttncdd',
        ],
        'Facturacion\\V1\\Rest\\Ttncdh\\Controller' => [
            'listener' => \Facturacion\V1\Rest\Ttncdh\TtncdhResource::class,
            'route_name' => 'facturacion.rest.ttncdh',
            'route_identifier_name' => 'ttncdh_id',
            'collection_name' => 'ttncdh',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Facturacion\V1\Rest\Ttncdh\TtncdhEntity::class,
            'collection_class' => \Facturacion\V1\Rest\Ttncdh\TtncdhCollection::class,
            'service_name' => 'Ttncdh',
        ],
        'Facturacion\\V1\\Rest\\Ttncyd\\Controller' => [
            'listener' => \Facturacion\V1\Rest\Ttncyd\TtncydResource::class,
            'route_name' => 'facturacion.rest.ttncyd',
            'route_identifier_name' => 'ttncyd_id',
            'collection_name' => 'ttncyd',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Facturacion\V1\Rest\Ttncyd\TtncydEntity::class,
            'collection_class' => \Facturacion\V1\Rest\Ttncyd\TtncydCollection::class,
            'service_name' => 'Ttncyd',
        ],
        'Facturacion\\V1\\Rest\\Ttpedd\\Controller' => [
            'listener' => \Facturacion\V1\Rest\Ttpedd\TtpeddResource::class,
            'route_name' => 'facturacion.rest.ttpedd',
            'route_identifier_name' => 'ttpedd_id',
            'collection_name' => 'ttpedd',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Facturacion\V1\Rest\Ttpedd\TtpeddEntity::class,
            'collection_class' => \Facturacion\V1\Rest\Ttpedd\TtpeddCollection::class,
            'service_name' => 'Ttpedd',
        ],
        'Facturacion\\V1\\Rest\\Ttpedh\\Controller' => [
            'listener' => \Facturacion\V1\Rest\Ttpedh\TtpedhResource::class,
            'route_name' => 'facturacion.rest.ttpedh',
            'route_identifier_name' => 'ttpedh_id',
            'collection_name' => 'ttpedh',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Facturacion\V1\Rest\Ttpedh\TtpedhEntity::class,
            'collection_class' => \Facturacion\V1\Rest\Ttpedh\TtpedhCollection::class,
            'service_name' => 'Ttpedh',
        ],
        'Facturacion\\V1\\Rest\\Ttptov\\Controller' => [
            'listener' => \Facturacion\V1\Rest\Ttptov\TtptovResource::class,
            'route_name' => 'facturacion.rest.ttptov',
            'route_identifier_name' => 'ttptov_id',
            'collection_name' => 'ttptov',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Facturacion\V1\Rest\Ttptov\TtptovEntity::class,
            'collection_class' => \Facturacion\V1\Rest\Ttptov\TtptovCollection::class,
            'service_name' => 'Ttptov',
        ],
        'Facturacion\\V1\\Rest\\Ttpuem\\Controller' => [
            'listener' => \Facturacion\V1\Rest\Ttpuem\TtpuemResource::class,
            'route_name' => 'facturacion.rest.ttpuem',
            'route_identifier_name' => 'ttpuem_id',
            'collection_name' => 'ttpuem',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Facturacion\V1\Rest\Ttpuem\TtpuemEntity::class,
            'collection_class' => \Facturacion\V1\Rest\Ttpuem\TtpuemCollection::class,
            'service_name' => 'Ttpuem',
        ],
        'Facturacion\\V1\\Rest\\Ttrvtd\\Controller' => [
            'listener' => \Facturacion\V1\Rest\Ttrvtd\TtrvtdResource::class,
            'route_name' => 'facturacion.rest.ttrvtd',
            'route_identifier_name' => 'ttrvtd_id',
            'collection_name' => 'ttrvtd',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Facturacion\V1\Rest\Ttrvtd\TtrvtdEntity::class,
            'collection_class' => \Facturacion\V1\Rest\Ttrvtd\TtrvtdCollection::class,
            'service_name' => 'Ttrvtd',
        ],
        'Facturacion\\V1\\Rest\\Ttrvth\\Controller' => [
            'listener' => \Facturacion\V1\Rest\Ttrvth\TtrvthResource::class,
            'route_name' => 'facturacion.rest.ttrvth',
            'route_identifier_name' => 'ttrvth_id',
            'collection_name' => 'ttrvth',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Facturacion\V1\Rest\Ttrvth\TtrvthEntity::class,
            'collection_class' => \Facturacion\V1\Rest\Ttrvth\TtrvthCollection::class,
            'service_name' => 'Ttrvth',
        ],
        'Facturacion\\V1\\Rest\\Tttido\\Controller' => [
            'listener' => \Facturacion\V1\Rest\Tttido\TttidoResource::class,
            'route_name' => 'facturacion.rest.tttido',
            'route_identifier_name' => 'tttido_id',
            'collection_name' => 'tttido',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Facturacion\V1\Rest\Tttido\TttidoEntity::class,
            'collection_class' => \Facturacion\V1\Rest\Tttido\TttidoCollection::class,
            'service_name' => 'Tttido',
        ],
    ],
    'zf-content-negotiation' => [
        'controllers' => [
            'Facturacion\\V1\\Rest\\Ttagen\\Controller' => 'HalJson',
            'Facturacion\\V1\\Rest\\Ttauto\\Controller' => 'HalJson',
            'Facturacion\\V1\\Rest\\Ttchcc\\Controller' => 'HalJson',
            'Facturacion\\V1\\Rest\\Ttcidi\\Controller' => 'HalJson',
            'Facturacion\\V1\\Rest\\Ttcpag\\Controller' => 'HalJson',
            'Facturacion\\V1\\Rest\\Ttdesc\\Controller' => 'HalJson',
            'Facturacion\\V1\\Rest\\Ttdist\\Controller' => 'HalJson',
            'Facturacion\\V1\\Rest\\Ttdpdb\\Controller' => 'HalJson',
            'Facturacion\\V1\\Rest\\Ttdscd\\Controller' => 'HalJson',
            'Facturacion\\V1\\Rest\\Ttdsch\\Controller' => 'HalJson',
            'Facturacion\\V1\\Rest\\Ttfpdi\\Controller' => 'HalJson',
            'Facturacion\\V1\\Rest\\Ttfvad\\Controller' => 'HalJson',
            'Facturacion\\V1\\Rest\\Ttfvah\\Controller' => 'HalJson',
            'Facturacion\\V1\\Rest\\Tthvtm\\Controller' => 'HalJson',
            'Facturacion\\V1\\Rest\\Ttlprd\\Controller' => 'HalJson',
            'Facturacion\\V1\\Rest\\Ttlprh\\Controller' => 'HalJson',
            'Facturacion\\V1\\Rest\\Ttmoau\\Controller' => 'HalJson',
            'Facturacion\\V1\\Rest\\Tthzon\\Controller' => 'HalJson',
            'Facturacion\\V1\\Rest\\Ttmovc\\Controller' => 'HalJson',
            'Facturacion\\V1\\Rest\\Ttncdd\\Controller' => 'HalJson',
            'Facturacion\\V1\\Rest\\Ttncdh\\Controller' => 'HalJson',
            'Facturacion\\V1\\Rest\\Ttncyd\\Controller' => 'HalJson',
            'Facturacion\\V1\\Rest\\Ttpedd\\Controller' => 'HalJson',
            'Facturacion\\V1\\Rest\\Ttpedh\\Controller' => 'HalJson',
            'Facturacion\\V1\\Rest\\Ttptov\\Controller' => 'HalJson',
            'Facturacion\\V1\\Rest\\Ttpuem\\Controller' => 'HalJson',
            'Facturacion\\V1\\Rest\\Ttrvtd\\Controller' => 'HalJson',
            'Facturacion\\V1\\Rest\\Ttrvth\\Controller' => 'HalJson',
            'Facturacion\\V1\\Rest\\Tttido\\Controller' => 'HalJson',
        ],
        'accept_whitelist' => [
            'Facturacion\\V1\\Rest\\Ttagen\\Controller' => [
                0 => 'application/vnd.facturacion.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Facturacion\\V1\\Rest\\Ttauto\\Controller' => [
                0 => 'application/vnd.facturacion.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Facturacion\\V1\\Rest\\Ttchcc\\Controller' => [
                0 => 'application/vnd.facturacion.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Facturacion\\V1\\Rest\\Ttcidi\\Controller' => [
                0 => 'application/vnd.facturacion.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Facturacion\\V1\\Rest\\Ttcpag\\Controller' => [
                0 => 'application/vnd.facturacion.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Facturacion\\V1\\Rest\\Ttdesc\\Controller' => [
                0 => 'application/vnd.facturacion.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Facturacion\\V1\\Rest\\Ttdist\\Controller' => [
                0 => 'application/vnd.facturacion.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Facturacion\\V1\\Rest\\Ttdpdb\\Controller' => [
                0 => 'application/vnd.facturacion.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Facturacion\\V1\\Rest\\Ttdscd\\Controller' => [
                0 => 'application/vnd.facturacion.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Facturacion\\V1\\Rest\\Ttdsch\\Controller' => [
                0 => 'application/vnd.facturacion.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Facturacion\\V1\\Rest\\Ttfpdi\\Controller' => [
                0 => 'application/vnd.facturacion.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Facturacion\\V1\\Rest\\Ttfvad\\Controller' => [
                0 => 'application/vnd.facturacion.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Facturacion\\V1\\Rest\\Ttfvah\\Controller' => [
                0 => 'application/vnd.facturacion.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Facturacion\\V1\\Rest\\Tthvtm\\Controller' => [
                0 => 'application/vnd.facturacion.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Facturacion\\V1\\Rest\\Ttlprd\\Controller' => [
                0 => 'application/vnd.facturacion.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Facturacion\\V1\\Rest\\Ttlprh\\Controller' => [
                0 => 'application/vnd.facturacion.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Facturacion\\V1\\Rest\\Ttmoau\\Controller' => [
                0 => 'application/vnd.facturacion.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Facturacion\\V1\\Rest\\Tthzon\\Controller' => [
                0 => 'application/vnd.facturacion.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Facturacion\\V1\\Rest\\Ttmovc\\Controller' => [
                0 => 'application/vnd.facturacion.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Facturacion\\V1\\Rest\\Ttncdd\\Controller' => [
                0 => 'application/vnd.facturacion.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Facturacion\\V1\\Rest\\Ttncdh\\Controller' => [
                0 => 'application/vnd.facturacion.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Facturacion\\V1\\Rest\\Ttncyd\\Controller' => [
                0 => 'application/vnd.facturacion.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Facturacion\\V1\\Rest\\Ttpedd\\Controller' => [
                0 => 'application/vnd.facturacion.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Facturacion\\V1\\Rest\\Ttpedh\\Controller' => [
                0 => 'application/vnd.facturacion.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Facturacion\\V1\\Rest\\Ttptov\\Controller' => [
                0 => 'application/vnd.facturacion.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Facturacion\\V1\\Rest\\Ttpuem\\Controller' => [
                0 => 'application/vnd.facturacion.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Facturacion\\V1\\Rest\\Ttrvtd\\Controller' => [
                0 => 'application/vnd.facturacion.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Facturacion\\V1\\Rest\\Ttrvth\\Controller' => [
                0 => 'application/vnd.facturacion.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Facturacion\\V1\\Rest\\Tttido\\Controller' => [
                0 => 'application/vnd.facturacion.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
        ],
        'content_type_whitelist' => [
            'Facturacion\\V1\\Rest\\Ttagen\\Controller' => [
                0 => 'application/vnd.facturacion.v1+json',
                1 => 'application/json',
            ],
            'Facturacion\\V1\\Rest\\Ttauto\\Controller' => [
                0 => 'application/vnd.facturacion.v1+json',
                1 => 'application/json',
            ],
            'Facturacion\\V1\\Rest\\Ttchcc\\Controller' => [
                0 => 'application/vnd.facturacion.v1+json',
                1 => 'application/json',
            ],
            'Facturacion\\V1\\Rest\\Ttcidi\\Controller' => [
                0 => 'application/vnd.facturacion.v1+json',
                1 => 'application/json',
            ],
            'Facturacion\\V1\\Rest\\Ttcpag\\Controller' => [
                0 => 'application/vnd.facturacion.v1+json',
                1 => 'application/json',
            ],
            'Facturacion\\V1\\Rest\\Ttdesc\\Controller' => [
                0 => 'application/vnd.facturacion.v1+json',
                1 => 'application/json',
            ],
            'Facturacion\\V1\\Rest\\Ttdist\\Controller' => [
                0 => 'application/vnd.facturacion.v1+json',
                1 => 'application/json',
            ],
            'Facturacion\\V1\\Rest\\Ttdpdb\\Controller' => [
                0 => 'application/vnd.facturacion.v1+json',
                1 => 'application/json',
            ],
            'Facturacion\\V1\\Rest\\Ttdscd\\Controller' => [
                0 => 'application/vnd.facturacion.v1+json',
                1 => 'application/json',
            ],
            'Facturacion\\V1\\Rest\\Ttdsch\\Controller' => [
                0 => 'application/vnd.facturacion.v1+json',
                1 => 'application/json',
            ],
            'Facturacion\\V1\\Rest\\Ttfpdi\\Controller' => [
                0 => 'application/vnd.facturacion.v1+json',
                1 => 'application/json',
            ],
            'Facturacion\\V1\\Rest\\Ttfvad\\Controller' => [
                0 => 'application/vnd.facturacion.v1+json',
                1 => 'application/json',
            ],
            'Facturacion\\V1\\Rest\\Ttfvah\\Controller' => [
                0 => 'application/vnd.facturacion.v1+json',
                1 => 'application/json',
            ],
            'Facturacion\\V1\\Rest\\Tthvtm\\Controller' => [
                0 => 'application/vnd.facturacion.v1+json',
                1 => 'application/json',
            ],
            'Facturacion\\V1\\Rest\\Ttlprd\\Controller' => [
                0 => 'application/vnd.facturacion.v1+json',
                1 => 'application/json',
            ],
            'Facturacion\\V1\\Rest\\Ttlprh\\Controller' => [
                0 => 'application/vnd.facturacion.v1+json',
                1 => 'application/json',
            ],
            'Facturacion\\V1\\Rest\\Ttmoau\\Controller' => [
                0 => 'application/vnd.facturacion.v1+json',
                1 => 'application/json',
            ],
            'Facturacion\\V1\\Rest\\Tthzon\\Controller' => [
                0 => 'application/vnd.facturacion.v1+json',
                1 => 'application/json',
            ],
            'Facturacion\\V1\\Rest\\Ttmovc\\Controller' => [
                0 => 'application/vnd.facturacion.v1+json',
                1 => 'application/json',
            ],
            'Facturacion\\V1\\Rest\\Ttncdd\\Controller' => [
                0 => 'application/vnd.facturacion.v1+json',
                1 => 'application/json',
            ],
            'Facturacion\\V1\\Rest\\Ttncdh\\Controller' => [
                0 => 'application/vnd.facturacion.v1+json',
                1 => 'application/json',
            ],
            'Facturacion\\V1\\Rest\\Ttncyd\\Controller' => [
                0 => 'application/vnd.facturacion.v1+json',
                1 => 'application/json',
            ],
            'Facturacion\\V1\\Rest\\Ttpedd\\Controller' => [
                0 => 'application/vnd.facturacion.v1+json',
                1 => 'application/json',
            ],
            'Facturacion\\V1\\Rest\\Ttpedh\\Controller' => [
                0 => 'application/vnd.facturacion.v1+json',
                1 => 'application/json',
            ],
            'Facturacion\\V1\\Rest\\Ttptov\\Controller' => [
                0 => 'application/vnd.facturacion.v1+json',
                1 => 'application/json',
            ],
            'Facturacion\\V1\\Rest\\Ttpuem\\Controller' => [
                0 => 'application/vnd.facturacion.v1+json',
                1 => 'application/json',
            ],
            'Facturacion\\V1\\Rest\\Ttrvtd\\Controller' => [
                0 => 'application/vnd.facturacion.v1+json',
                1 => 'application/json',
            ],
            'Facturacion\\V1\\Rest\\Ttrvth\\Controller' => [
                0 => 'application/vnd.facturacion.v1+json',
                1 => 'application/json',
            ],
            'Facturacion\\V1\\Rest\\Tttido\\Controller' => [
                0 => 'application/vnd.facturacion.v1+json',
                1 => 'application/json',
            ],
        ],
    ],
    'zf-hal' => [
        'metadata_map' => [
            \Facturacion\V1\Rest\Ttagen\TtagenEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'facturacion.rest.ttagen',
                'route_identifier_name' => 'ttagen_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Facturacion\V1\Rest\Ttagen\TtagenCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'facturacion.rest.ttagen',
                'route_identifier_name' => 'ttagen_id',
                'is_collection' => true,
            ],
            \Facturacion\V1\Rest\Ttauto\TtautoEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'facturacion.rest.ttauto',
                'route_identifier_name' => 'ttauto_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Facturacion\V1\Rest\Ttauto\TtautoCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'facturacion.rest.ttauto',
                'route_identifier_name' => 'ttauto_id',
                'is_collection' => true,
            ],
            \Facturacion\V1\Rest\Ttchcc\TtchccEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'facturacion.rest.ttchcc',
                'route_identifier_name' => 'ttchcc_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Facturacion\V1\Rest\Ttchcc\TtchccCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'facturacion.rest.ttchcc',
                'route_identifier_name' => 'ttchcc_id',
                'is_collection' => true,
            ],
            \Facturacion\V1\Rest\Ttcidi\TtcidiEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'facturacion.rest.ttcidi',
                'route_identifier_name' => 'ttcidi_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Facturacion\V1\Rest\Ttcidi\TtcidiCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'facturacion.rest.ttcidi',
                'route_identifier_name' => 'ttcidi_id',
                'is_collection' => true,
            ],
            \Facturacion\V1\Rest\Ttcpag\TtcpagEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'facturacion.rest.ttcpag',
                'route_identifier_name' => 'ttcpag_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Facturacion\V1\Rest\Ttcpag\TtcpagCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'facturacion.rest.ttcpag',
                'route_identifier_name' => 'ttcpag_id',
                'is_collection' => true,
            ],
            \Facturacion\V1\Rest\Ttdesc\TtdescEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'facturacion.rest.ttdesc',
                'route_identifier_name' => 'ttdesc_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Facturacion\V1\Rest\Ttdesc\TtdescCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'facturacion.rest.ttdesc',
                'route_identifier_name' => 'ttdesc_id',
                'is_collection' => true,
            ],
            \Facturacion\V1\Rest\Ttdist\TtdistEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'facturacion.rest.ttdist',
                'route_identifier_name' => 'ttdist_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Facturacion\V1\Rest\Ttdist\TtdistCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'facturacion.rest.ttdist',
                'route_identifier_name' => 'ttdist_id',
                'is_collection' => true,
            ],
            \Facturacion\V1\Rest\Ttdpdb\TtdpdbEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'facturacion.rest.ttdpdb',
                'route_identifier_name' => 'ttdpdb_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Facturacion\V1\Rest\Ttdpdb\TtdpdbCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'facturacion.rest.ttdpdb',
                'route_identifier_name' => 'ttdpdb_id',
                'is_collection' => true,
            ],
            \Facturacion\V1\Rest\Ttdscd\TtdscdEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'facturacion.rest.ttdscd',
                'route_identifier_name' => 'ttdscd_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Facturacion\V1\Rest\Ttdscd\TtdscdCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'facturacion.rest.ttdscd',
                'route_identifier_name' => 'ttdscd_id',
                'is_collection' => true,
            ],
            \Facturacion\V1\Rest\Ttdsch\TtdschEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'facturacion.rest.ttdsch',
                'route_identifier_name' => 'ttdsch_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Facturacion\V1\Rest\Ttdsch\TtdschCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'facturacion.rest.ttdsch',
                'route_identifier_name' => 'ttdsch_id',
                'is_collection' => true,
            ],
            \Facturacion\V1\Rest\Ttfpdi\TtfpdiEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'facturacion.rest.ttfpdi',
                'route_identifier_name' => 'ttfpdi_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Facturacion\V1\Rest\Ttfpdi\TtfpdiCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'facturacion.rest.ttfpdi',
                'route_identifier_name' => 'ttfpdi_id',
                'is_collection' => true,
            ],
            \Facturacion\V1\Rest\Ttfvad\TtfvadEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'facturacion.rest.ttfvad',
                'route_identifier_name' => 'ttfvad_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Facturacion\V1\Rest\Ttfvad\TtfvadCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'facturacion.rest.ttfvad',
                'route_identifier_name' => 'ttfvad_id',
                'is_collection' => true,
            ],
            \Facturacion\V1\Rest\Ttfvah\TtfvahEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'facturacion.rest.ttfvah',
                'route_identifier_name' => 'ttfvah_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Facturacion\V1\Rest\Ttfvah\TtfvahCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'facturacion.rest.ttfvah',
                'route_identifier_name' => 'ttfvah_id',
                'is_collection' => true,
            ],
            \Facturacion\V1\Rest\Tthvtm\TthvtmEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'facturacion.rest.tthvtm',
                'route_identifier_name' => 'tthvtm_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Facturacion\V1\Rest\Tthvtm\TthvtmCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'facturacion.rest.tthvtm',
                'route_identifier_name' => 'tthvtm_id',
                'is_collection' => true,
            ],
            \Facturacion\V1\Rest\Ttlprd\TtlprdEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'facturacion.rest.ttlprd',
                'route_identifier_name' => 'ttlprd_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Facturacion\V1\Rest\Ttlprd\TtlprdCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'facturacion.rest.ttlprd',
                'route_identifier_name' => 'ttlprd_id',
                'is_collection' => true,
            ],
            \Facturacion\V1\Rest\Ttlprh\TtlprhEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'facturacion.rest.ttlprh',
                'route_identifier_name' => 'ttlprh_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Facturacion\V1\Rest\Ttlprh\TtlprhCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'facturacion.rest.ttlprh',
                'route_identifier_name' => 'ttlprh_id',
                'is_collection' => true,
            ],
            \Facturacion\V1\Rest\Ttmoau\TtmoauEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'facturacion.rest.ttmoau',
                'route_identifier_name' => 'ttmoau_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Facturacion\V1\Rest\Ttmoau\TtmoauCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'facturacion.rest.ttmoau',
                'route_identifier_name' => 'ttmoau_id',
                'is_collection' => true,
            ],
            \Facturacion\V1\Rest\Tthzon\TthzonEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'facturacion.rest.tthzon',
                'route_identifier_name' => 'tthzon_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Facturacion\V1\Rest\Tthzon\TthzonCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'facturacion.rest.tthzon',
                'route_identifier_name' => 'tthzon_id',
                'is_collection' => true,
            ],
            \Facturacion\V1\Rest\Ttmovc\TtmovcEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'facturacion.rest.ttmovc',
                'route_identifier_name' => 'ttmovc_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Facturacion\V1\Rest\Ttmovc\TtmovcCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'facturacion.rest.ttmovc',
                'route_identifier_name' => 'ttmovc_id',
                'is_collection' => true,
            ],
            \Facturacion\V1\Rest\Ttncdd\TtncddEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'facturacion.rest.ttncdd',
                'route_identifier_name' => 'ttncdd_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Facturacion\V1\Rest\Ttncdd\TtncddCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'facturacion.rest.ttncdd',
                'route_identifier_name' => 'ttncdd_id',
                'is_collection' => true,
            ],
            \Facturacion\V1\Rest\Ttncdh\TtncdhEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'facturacion.rest.ttncdh',
                'route_identifier_name' => 'ttncdh_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Facturacion\V1\Rest\Ttncdh\TtncdhCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'facturacion.rest.ttncdh',
                'route_identifier_name' => 'ttncdh_id',
                'is_collection' => true,
            ],
            \Facturacion\V1\Rest\Ttncyd\TtncydEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'facturacion.rest.ttncyd',
                'route_identifier_name' => 'ttncyd_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Facturacion\V1\Rest\Ttncyd\TtncydCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'facturacion.rest.ttncyd',
                'route_identifier_name' => 'ttncyd_id',
                'is_collection' => true,
            ],
            \Facturacion\V1\Rest\Ttpedd\TtpeddEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'facturacion.rest.ttpedd',
                'route_identifier_name' => 'ttpedd_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Facturacion\V1\Rest\Ttpedd\TtpeddCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'facturacion.rest.ttpedd',
                'route_identifier_name' => 'ttpedd_id',
                'is_collection' => true,
            ],
            \Facturacion\V1\Rest\Ttpedh\TtpedhEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'facturacion.rest.ttpedh',
                'route_identifier_name' => 'ttpedh_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Facturacion\V1\Rest\Ttpedh\TtpedhCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'facturacion.rest.ttpedh',
                'route_identifier_name' => 'ttpedh_id',
                'is_collection' => true,
            ],
            \Facturacion\V1\Rest\Ttptov\TtptovEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'facturacion.rest.ttptov',
                'route_identifier_name' => 'ttptov_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Facturacion\V1\Rest\Ttptov\TtptovCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'facturacion.rest.ttptov',
                'route_identifier_name' => 'ttptov_id',
                'is_collection' => true,
            ],
            \Facturacion\V1\Rest\Ttpuem\TtpuemEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'facturacion.rest.ttpuem',
                'route_identifier_name' => 'ttpuem_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Facturacion\V1\Rest\Ttpuem\TtpuemCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'facturacion.rest.ttpuem',
                'route_identifier_name' => 'ttpuem_id',
                'is_collection' => true,
            ],
            \Facturacion\V1\Rest\Ttrvtd\TtrvtdEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'facturacion.rest.ttrvtd',
                'route_identifier_name' => 'ttrvtd_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Facturacion\V1\Rest\Ttrvtd\TtrvtdCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'facturacion.rest.ttrvtd',
                'route_identifier_name' => 'ttrvtd_id',
                'is_collection' => true,
            ],
            \Facturacion\V1\Rest\Ttrvth\TtrvthEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'facturacion.rest.ttrvth',
                'route_identifier_name' => 'ttrvth_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Facturacion\V1\Rest\Ttrvth\TtrvthCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'facturacion.rest.ttrvth',
                'route_identifier_name' => 'ttrvth_id',
                'is_collection' => true,
            ],
            \Facturacion\V1\Rest\Tttido\TttidoEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'facturacion.rest.tttido',
                'route_identifier_name' => 'tttido_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Facturacion\V1\Rest\Tttido\TttidoCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'facturacion.rest.tttido',
                'route_identifier_name' => 'tttido_id',
                'is_collection' => true,
            ],
        ],
    ],
];
