<?php
return [
    'service_manager' => [
        'factories' => [
            \Compras\V1\Rest\Tkfcnd\TkfcndResource::class => \Compras\V1\Rest\Tkfcnd\TkfcndResourceFactory::class,
            \Compras\V1\Rest\Tkfcnh\TkfcnhResource::class => \Compras\V1\Rest\Tkfcnh\TkfcnhResourceFactory::class,
            \Compras\V1\Rest\Tkfpid\TkfpidResource::class => \Compras\V1\Rest\Tkfpid\TkfpidResourceFactory::class,
            \Compras\V1\Rest\Tkfpig\TkfpigResource::class => \Compras\V1\Rest\Tkfpig\TkfpigResourceFactory::class,
            \Compras\V1\Rest\Tkfpih\TkfpihResource::class => \Compras\V1\Rest\Tkfpih\TkfpihResourceFactory::class,
            \Compras\V1\Rest\Tkfrod\TkfrodResource::class => \Compras\V1\Rest\Tkfrod\TkfrodResourceFactory::class,
            \Compras\V1\Rest\Tkfroh\TkfrohResource::class => \Compras\V1\Rest\Tkfroh\TkfrohResourceFactory::class,
            \Compras\V1\Rest\Tktido\TktidoResource::class => \Compras\V1\Rest\Tktido\TktidoResourceFactory::class,
            \Compras\V1\Rest\Tkvcnd\TkvcndResource::class => \Compras\V1\Rest\Tkvcnd\TkvcndResourceFactory::class,
            \Compras\V1\Rest\Tkvcnh\TkvcnhResource::class => \Compras\V1\Rest\Tkvcnh\TkvcnhResourceFactory::class,
            \Compras\V1\Rest\Tkvpid\TkvpidResource::class => \Compras\V1\Rest\Tkvpid\TkvpidResourceFactory::class,
            \Compras\V1\Rest\Tkvpig\TkvpigResource::class => \Compras\V1\Rest\Tkvpig\TkvpigResourceFactory::class,
            \Compras\V1\Rest\Tkvpih\TkvpihResource::class => \Compras\V1\Rest\Tkvpih\TkvpihResourceFactory::class,
            \Compras\V1\Rest\Tkvrod\TkvrodResource::class => \Compras\V1\Rest\Tkvrod\TkvrodResourceFactory::class,
            \Compras\V1\Rest\Tkvroh\TkvrohResource::class => \Compras\V1\Rest\Tkvroh\TkvrohResourceFactory::class,
        ],
    ],
    'router' => [
        'routes' => [
            'compras.rest.tkfcnd' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tkfcnd[/:tkfcnd_id]',
                    'defaults' => [
                        'controller' => 'Compras\\V1\\Rest\\Tkfcnd\\Controller',
                    ],
                ],
            ],
            'compras.rest.tkfcnh' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tkfcnh[/:tkfcnh_id]',
                    'defaults' => [
                        'controller' => 'Compras\\V1\\Rest\\Tkfcnh\\Controller',
                    ],
                ],
            ],
            'compras.rest.tkfpid' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tkfpid[/:tkfpid_id]',
                    'defaults' => [
                        'controller' => 'Compras\\V1\\Rest\\Tkfpid\\Controller',
                    ],
                ],
            ],
            'compras.rest.tkfpig' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tkfpig[/:tkfpig_id]',
                    'defaults' => [
                        'controller' => 'Compras\\V1\\Rest\\Tkfpig\\Controller',
                    ],
                ],
            ],
            'compras.rest.tkfpih' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tkfpih[/:tkfpih_id]',
                    'defaults' => [
                        'controller' => 'Compras\\V1\\Rest\\Tkfpih\\Controller',
                    ],
                ],
            ],
            'compras.rest.tkfrod' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tkfrod[/:tkfrod_id]',
                    'defaults' => [
                        'controller' => 'Compras\\V1\\Rest\\Tkfrod\\Controller',
                    ],
                ],
            ],
            'compras.rest.tkfroh' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tkfroh[/:tkfroh_id]',
                    'defaults' => [
                        'controller' => 'Compras\\V1\\Rest\\Tkfroh\\Controller',
                    ],
                ],
            ],
            'compras.rest.tktido' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tktido[/:tktido_id]',
                    'defaults' => [
                        'controller' => 'Compras\\V1\\Rest\\Tktido\\Controller',
                    ],
                ],
            ],
            'compras.rest.tkvcnd' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tkvcnd[/:tkvcnd_id]',
                    'defaults' => [
                        'controller' => 'Compras\\V1\\Rest\\Tkvcnd\\Controller',
                    ],
                ],
            ],
            'compras.rest.tkvcnh' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tkvcnh[/:tkvcnh_id]',
                    'defaults' => [
                        'controller' => 'Compras\\V1\\Rest\\Tkvcnh\\Controller',
                    ],
                ],
            ],
            'compras.rest.tkvpid' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tkvpid[/:tkvpid_id]',
                    'defaults' => [
                        'controller' => 'Compras\\V1\\Rest\\Tkvpid\\Controller',
                    ],
                ],
            ],
            'compras.rest.tkvpig' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tkvpig[/:tkvpig_id]',
                    'defaults' => [
                        'controller' => 'Compras\\V1\\Rest\\Tkvpig\\Controller',
                    ],
                ],
            ],
            'compras.rest.tkvpih' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tkvpih[/:tkvpih_id]',
                    'defaults' => [
                        'controller' => 'Compras\\V1\\Rest\\Tkvpih\\Controller',
                    ],
                ],
            ],
            'compras.rest.tkvrod' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tkvrod[/:tkvrod_id]',
                    'defaults' => [
                        'controller' => 'Compras\\V1\\Rest\\Tkvrod\\Controller',
                    ],
                ],
            ],
            'compras.rest.tkvroh' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tkvroh[/:tkvroh_id]',
                    'defaults' => [
                        'controller' => 'Compras\\V1\\Rest\\Tkvroh\\Controller',
                    ],
                ],
            ],
        ],
    ],
    'zf-versioning' => [
        'uri' => [
            0 => 'compras.rest.tkfcnd',
            1 => 'compras.rest.tkfcnh',
            2 => 'compras.rest.tkfpid',
            3 => 'compras.rest.tkfpig',
            4 => 'compras.rest.tkfpih',
            5 => 'compras.rest.tkfrod',
            6 => 'compras.rest.tkfroh',
            7 => 'compras.rest.tktido',
            8 => 'compras.rest.tkvcnd',
            9 => 'compras.rest.tkvcnh',
            10 => 'compras.rest.tkvpid',
            11 => 'compras.rest.tkvpig',
            12 => 'compras.rest.tkvpih',
            13 => 'compras.rest.tkvrod',
            14 => 'compras.rest.tkvroh',
        ],
    ],
    'zf-rest' => [
        'Compras\\V1\\Rest\\Tkfcnd\\Controller' => [
            'listener' => \Compras\V1\Rest\Tkfcnd\TkfcndResource::class,
            'route_name' => 'compras.rest.tkfcnd',
            'route_identifier_name' => 'tkfcnd_id',
            'collection_name' => 'tkfcnd',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Compras\V1\Rest\Tkfcnd\TkfcndEntity::class,
            'collection_class' => \Compras\V1\Rest\Tkfcnd\TkfcndCollection::class,
            'service_name' => 'Tkfcnd',
        ],
        'Compras\\V1\\Rest\\Tkfcnh\\Controller' => [
            'listener' => \Compras\V1\Rest\Tkfcnh\TkfcnhResource::class,
            'route_name' => 'compras.rest.tkfcnh',
            'route_identifier_name' => 'tkfcnh_id',
            'collection_name' => 'tkfcnh',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Compras\V1\Rest\Tkfcnh\TkfcnhEntity::class,
            'collection_class' => \Compras\V1\Rest\Tkfcnh\TkfcnhCollection::class,
            'service_name' => 'Tkfcnh',
        ],
        'Compras\\V1\\Rest\\Tkfpid\\Controller' => [
            'listener' => \Compras\V1\Rest\Tkfpid\TkfpidResource::class,
            'route_name' => 'compras.rest.tkfpid',
            'route_identifier_name' => 'tkfpid_id',
            'collection_name' => 'tkfpid',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Compras\V1\Rest\Tkfpid\TkfpidEntity::class,
            'collection_class' => \Compras\V1\Rest\Tkfpid\TkfpidCollection::class,
            'service_name' => 'Tkfpid',
        ],
        'Compras\\V1\\Rest\\Tkfpig\\Controller' => [
            'listener' => \Compras\V1\Rest\Tkfpig\TkfpigResource::class,
            'route_name' => 'compras.rest.tkfpig',
            'route_identifier_name' => 'tkfpig_id',
            'collection_name' => 'tkfpig',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Compras\V1\Rest\Tkfpig\TkfpigEntity::class,
            'collection_class' => \Compras\V1\Rest\Tkfpig\TkfpigCollection::class,
            'service_name' => 'Tkfpig',
        ],
        'Compras\\V1\\Rest\\Tkfpih\\Controller' => [
            'listener' => \Compras\V1\Rest\Tkfpih\TkfpihResource::class,
            'route_name' => 'compras.rest.tkfpih',
            'route_identifier_name' => 'tkfpih_id',
            'collection_name' => 'tkfpih',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Compras\V1\Rest\Tkfpih\TkfpihEntity::class,
            'collection_class' => \Compras\V1\Rest\Tkfpih\TkfpihCollection::class,
            'service_name' => 'Tkfpih',
        ],
        'Compras\\V1\\Rest\\Tkfrod\\Controller' => [
            'listener' => \Compras\V1\Rest\Tkfrod\TkfrodResource::class,
            'route_name' => 'compras.rest.tkfrod',
            'route_identifier_name' => 'tkfrod_id',
            'collection_name' => 'tkfrod',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Compras\V1\Rest\Tkfrod\TkfrodEntity::class,
            'collection_class' => \Compras\V1\Rest\Tkfrod\TkfrodCollection::class,
            'service_name' => 'Tkfrod',
        ],
        'Compras\\V1\\Rest\\Tkfroh\\Controller' => [
            'listener' => \Compras\V1\Rest\Tkfroh\TkfrohResource::class,
            'route_name' => 'compras.rest.tkfroh',
            'route_identifier_name' => 'tkfroh_id',
            'collection_name' => 'tkfroh',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Compras\V1\Rest\Tkfroh\TkfrohEntity::class,
            'collection_class' => \Compras\V1\Rest\Tkfroh\TkfrohCollection::class,
            'service_name' => 'Tkfroh',
        ],
        'Compras\\V1\\Rest\\Tktido\\Controller' => [
            'listener' => \Compras\V1\Rest\Tktido\TktidoResource::class,
            'route_name' => 'compras.rest.tktido',
            'route_identifier_name' => 'tktido_id',
            'collection_name' => 'tktido',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Compras\V1\Rest\Tktido\TktidoEntity::class,
            'collection_class' => \Compras\V1\Rest\Tktido\TktidoCollection::class,
            'service_name' => 'Tktido',
        ],
        'Compras\\V1\\Rest\\Tkvcnd\\Controller' => [
            'listener' => \Compras\V1\Rest\Tkvcnd\TkvcndResource::class,
            'route_name' => 'compras.rest.tkvcnd',
            'route_identifier_name' => 'tkvcnd_id',
            'collection_name' => 'tkvcnd',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Compras\V1\Rest\Tkvcnd\TkvcndEntity::class,
            'collection_class' => \Compras\V1\Rest\Tkvcnd\TkvcndCollection::class,
            'service_name' => 'Tkvcnd',
        ],
        'Compras\\V1\\Rest\\Tkvcnh\\Controller' => [
            'listener' => \Compras\V1\Rest\Tkvcnh\TkvcnhResource::class,
            'route_name' => 'compras.rest.tkvcnh',
            'route_identifier_name' => 'tkvcnh_id',
            'collection_name' => 'tkvcnh',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Compras\V1\Rest\Tkvcnh\TkvcnhEntity::class,
            'collection_class' => \Compras\V1\Rest\Tkvcnh\TkvcnhCollection::class,
            'service_name' => 'Tkvcnh',
        ],
        'Compras\\V1\\Rest\\Tkvpid\\Controller' => [
            'listener' => \Compras\V1\Rest\Tkvpid\TkvpidResource::class,
            'route_name' => 'compras.rest.tkvpid',
            'route_identifier_name' => 'tkvpid_id',
            'collection_name' => 'tkvpid',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Compras\V1\Rest\Tkvpid\TkvpidEntity::class,
            'collection_class' => \Compras\V1\Rest\Tkvpid\TkvpidCollection::class,
            'service_name' => 'Tkvpid',
        ],
        'Compras\\V1\\Rest\\Tkvpig\\Controller' => [
            'listener' => \Compras\V1\Rest\Tkvpig\TkvpigResource::class,
            'route_name' => 'compras.rest.tkvpig',
            'route_identifier_name' => 'tkvpig_id',
            'collection_name' => 'tkvpig',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Compras\V1\Rest\Tkvpig\TkvpigEntity::class,
            'collection_class' => \Compras\V1\Rest\Tkvpig\TkvpigCollection::class,
            'service_name' => 'Tkvpig',
        ],
        'Compras\\V1\\Rest\\Tkvpih\\Controller' => [
            'listener' => \Compras\V1\Rest\Tkvpih\TkvpihResource::class,
            'route_name' => 'compras.rest.tkvpih',
            'route_identifier_name' => 'tkvpih_id',
            'collection_name' => 'tkvpih',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Compras\V1\Rest\Tkvpih\TkvpihEntity::class,
            'collection_class' => \Compras\V1\Rest\Tkvpih\TkvpihCollection::class,
            'service_name' => 'Tkvpih',
        ],
        'Compras\\V1\\Rest\\Tkvrod\\Controller' => [
            'listener' => \Compras\V1\Rest\Tkvrod\TkvrodResource::class,
            'route_name' => 'compras.rest.tkvrod',
            'route_identifier_name' => 'tkvrod_id',
            'collection_name' => 'tkvrod',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Compras\V1\Rest\Tkvrod\TkvrodEntity::class,
            'collection_class' => \Compras\V1\Rest\Tkvrod\TkvrodCollection::class,
            'service_name' => 'Tkvrod',
        ],
        'Compras\\V1\\Rest\\Tkvroh\\Controller' => [
            'listener' => \Compras\V1\Rest\Tkvroh\TkvrohResource::class,
            'route_name' => 'compras.rest.tkvroh',
            'route_identifier_name' => 'tkvroh_id',
            'collection_name' => 'tkvroh',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Compras\V1\Rest\Tkvroh\TkvrohEntity::class,
            'collection_class' => \Compras\V1\Rest\Tkvroh\TkvrohCollection::class,
            'service_name' => 'Tkvroh',
        ],
    ],
    'zf-content-negotiation' => [
        'controllers' => [
            'Compras\\V1\\Rest\\Tkfcnd\\Controller' => 'HalJson',
            'Compras\\V1\\Rest\\Tkfcnh\\Controller' => 'HalJson',
            'Compras\\V1\\Rest\\Tkfpid\\Controller' => 'HalJson',
            'Compras\\V1\\Rest\\Tkfpig\\Controller' => 'HalJson',
            'Compras\\V1\\Rest\\Tkfpih\\Controller' => 'HalJson',
            'Compras\\V1\\Rest\\Tkfrod\\Controller' => 'HalJson',
            'Compras\\V1\\Rest\\Tkfroh\\Controller' => 'HalJson',
            'Compras\\V1\\Rest\\Tktido\\Controller' => 'HalJson',
            'Compras\\V1\\Rest\\Tkvcnd\\Controller' => 'HalJson',
            'Compras\\V1\\Rest\\Tkvcnh\\Controller' => 'HalJson',
            'Compras\\V1\\Rest\\Tkvpid\\Controller' => 'HalJson',
            'Compras\\V1\\Rest\\Tkvpig\\Controller' => 'HalJson',
            'Compras\\V1\\Rest\\Tkvpih\\Controller' => 'HalJson',
            'Compras\\V1\\Rest\\Tkvrod\\Controller' => 'HalJson',
            'Compras\\V1\\Rest\\Tkvroh\\Controller' => 'HalJson',
        ],
        'accept_whitelist' => [
            'Compras\\V1\\Rest\\Tkfcnd\\Controller' => [
                0 => 'application/vnd.compras.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Compras\\V1\\Rest\\Tkfcnh\\Controller' => [
                0 => 'application/vnd.compras.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Compras\\V1\\Rest\\Tkfpid\\Controller' => [
                0 => 'application/vnd.compras.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Compras\\V1\\Rest\\Tkfpig\\Controller' => [
                0 => 'application/vnd.compras.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Compras\\V1\\Rest\\Tkfpih\\Controller' => [
                0 => 'application/vnd.compras.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Compras\\V1\\Rest\\Tkfrod\\Controller' => [
                0 => 'application/vnd.compras.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Compras\\V1\\Rest\\Tkfroh\\Controller' => [
                0 => 'application/vnd.compras.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Compras\\V1\\Rest\\Tktido\\Controller' => [
                0 => 'application/vnd.compras.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Compras\\V1\\Rest\\Tkvcnd\\Controller' => [
                0 => 'application/vnd.compras.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Compras\\V1\\Rest\\Tkvcnh\\Controller' => [
                0 => 'application/vnd.compras.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Compras\\V1\\Rest\\Tkvpid\\Controller' => [
                0 => 'application/vnd.compras.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Compras\\V1\\Rest\\Tkvpig\\Controller' => [
                0 => 'application/vnd.compras.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Compras\\V1\\Rest\\Tkvpih\\Controller' => [
                0 => 'application/vnd.compras.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Compras\\V1\\Rest\\Tkvrod\\Controller' => [
                0 => 'application/vnd.compras.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Compras\\V1\\Rest\\Tkvroh\\Controller' => [
                0 => 'application/vnd.compras.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
        ],
        'content_type_whitelist' => [
            'Compras\\V1\\Rest\\Tkfcnd\\Controller' => [
                0 => 'application/vnd.compras.v1+json',
                1 => 'application/json',
            ],
            'Compras\\V1\\Rest\\Tkfcnh\\Controller' => [
                0 => 'application/vnd.compras.v1+json',
                1 => 'application/json',
            ],
            'Compras\\V1\\Rest\\Tkfpid\\Controller' => [
                0 => 'application/vnd.compras.v1+json',
                1 => 'application/json',
            ],
            'Compras\\V1\\Rest\\Tkfpig\\Controller' => [
                0 => 'application/vnd.compras.v1+json',
                1 => 'application/json',
            ],
            'Compras\\V1\\Rest\\Tkfpih\\Controller' => [
                0 => 'application/vnd.compras.v1+json',
                1 => 'application/json',
            ],
            'Compras\\V1\\Rest\\Tkfrod\\Controller' => [
                0 => 'application/vnd.compras.v1+json',
                1 => 'application/json',
            ],
            'Compras\\V1\\Rest\\Tkfroh\\Controller' => [
                0 => 'application/vnd.compras.v1+json',
                1 => 'application/json',
            ],
            'Compras\\V1\\Rest\\Tktido\\Controller' => [
                0 => 'application/vnd.compras.v1+json',
                1 => 'application/json',
            ],
            'Compras\\V1\\Rest\\Tkvcnd\\Controller' => [
                0 => 'application/vnd.compras.v1+json',
                1 => 'application/json',
            ],
            'Compras\\V1\\Rest\\Tkvcnh\\Controller' => [
                0 => 'application/vnd.compras.v1+json',
                1 => 'application/json',
            ],
            'Compras\\V1\\Rest\\Tkvpid\\Controller' => [
                0 => 'application/vnd.compras.v1+json',
                1 => 'application/json',
            ],
            'Compras\\V1\\Rest\\Tkvpig\\Controller' => [
                0 => 'application/vnd.compras.v1+json',
                1 => 'application/json',
            ],
            'Compras\\V1\\Rest\\Tkvpih\\Controller' => [
                0 => 'application/vnd.compras.v1+json',
                1 => 'application/json',
            ],
            'Compras\\V1\\Rest\\Tkvrod\\Controller' => [
                0 => 'application/vnd.compras.v1+json',
                1 => 'application/json',
            ],
            'Compras\\V1\\Rest\\Tkvroh\\Controller' => [
                0 => 'application/vnd.compras.v1+json',
                1 => 'application/json',
            ],
        ],
    ],
    'zf-hal' => [
        'metadata_map' => [
            \Compras\V1\Rest\Tkfcnd\TkfcndEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'compras.rest.tkfcnd',
                'route_identifier_name' => 'tkfcnd_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Compras\V1\Rest\Tkfcnd\TkfcndCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'compras.rest.tkfcnd',
                'route_identifier_name' => 'tkfcnd_id',
                'is_collection' => true,
            ],
            \Compras\V1\Rest\Tkfcnh\TkfcnhEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'compras.rest.tkfcnh',
                'route_identifier_name' => 'tkfcnh_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Compras\V1\Rest\Tkfcnh\TkfcnhCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'compras.rest.tkfcnh',
                'route_identifier_name' => 'tkfcnh_id',
                'is_collection' => true,
            ],
            \Compras\V1\Rest\Tkfpid\TkfpidEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'compras.rest.tkfpid',
                'route_identifier_name' => 'tkfpid_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Compras\V1\Rest\Tkfpid\TkfpidCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'compras.rest.tkfpid',
                'route_identifier_name' => 'tkfpid_id',
                'is_collection' => true,
            ],
            \Compras\V1\Rest\Tkfpig\TkfpigEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'compras.rest.tkfpig',
                'route_identifier_name' => 'tkfpig_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Compras\V1\Rest\Tkfpig\TkfpigCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'compras.rest.tkfpig',
                'route_identifier_name' => 'tkfpig_id',
                'is_collection' => true,
            ],
            \Compras\V1\Rest\Tkfpih\TkfpihEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'compras.rest.tkfpih',
                'route_identifier_name' => 'tkfpih_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Compras\V1\Rest\Tkfpih\TkfpihCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'compras.rest.tkfpih',
                'route_identifier_name' => 'tkfpih_id',
                'is_collection' => true,
            ],
            \Compras\V1\Rest\Tkfrod\TkfrodEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'compras.rest.tkfrod',
                'route_identifier_name' => 'tkfrod_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Compras\V1\Rest\Tkfrod\TkfrodCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'compras.rest.tkfrod',
                'route_identifier_name' => 'tkfrod_id',
                'is_collection' => true,
            ],
            \Compras\V1\Rest\Tkfroh\TkfrohEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'compras.rest.tkfroh',
                'route_identifier_name' => 'tkfroh_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Compras\V1\Rest\Tkfroh\TkfrohCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'compras.rest.tkfroh',
                'route_identifier_name' => 'tkfroh_id',
                'is_collection' => true,
            ],
            \Compras\V1\Rest\Tktido\TktidoEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'compras.rest.tktido',
                'route_identifier_name' => 'tktido_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Compras\V1\Rest\Tktido\TktidoCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'compras.rest.tktido',
                'route_identifier_name' => 'tktido_id',
                'is_collection' => true,
            ],
            \Compras\V1\Rest\Tkvcnd\TkvcndEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'compras.rest.tkvcnd',
                'route_identifier_name' => 'tkvcnd_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Compras\V1\Rest\Tkvcnd\TkvcndCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'compras.rest.tkvcnd',
                'route_identifier_name' => 'tkvcnd_id',
                'is_collection' => true,
            ],
            \Compras\V1\Rest\Tkvcnh\TkvcnhEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'compras.rest.tkvcnh',
                'route_identifier_name' => 'tkvcnh_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Compras\V1\Rest\Tkvcnh\TkvcnhCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'compras.rest.tkvcnh',
                'route_identifier_name' => 'tkvcnh_id',
                'is_collection' => true,
            ],
            \Compras\V1\Rest\Tkvpid\TkvpidEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'compras.rest.tkvpid',
                'route_identifier_name' => 'tkvpid_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Compras\V1\Rest\Tkvpid\TkvpidCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'compras.rest.tkvpid',
                'route_identifier_name' => 'tkvpid_id',
                'is_collection' => true,
            ],
            \Compras\V1\Rest\Tkvpig\TkvpigEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'compras.rest.tkvpig',
                'route_identifier_name' => 'tkvpig_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Compras\V1\Rest\Tkvpig\TkvpigCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'compras.rest.tkvpig',
                'route_identifier_name' => 'tkvpig_id',
                'is_collection' => true,
            ],
            \Compras\V1\Rest\Tkvpih\TkvpihEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'compras.rest.tkvpih',
                'route_identifier_name' => 'tkvpih_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Compras\V1\Rest\Tkvpih\TkvpihCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'compras.rest.tkvpih',
                'route_identifier_name' => 'tkvpih_id',
                'is_collection' => true,
            ],
            \Compras\V1\Rest\Tkvrod\TkvrodEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'compras.rest.tkvrod',
                'route_identifier_name' => 'tkvrod_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Compras\V1\Rest\Tkvrod\TkvrodCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'compras.rest.tkvrod',
                'route_identifier_name' => 'tkvrod_id',
                'is_collection' => true,
            ],
            \Compras\V1\Rest\Tkvroh\TkvrohEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'compras.rest.tkvroh',
                'route_identifier_name' => 'tkvroh_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Compras\V1\Rest\Tkvroh\TkvrohCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'compras.rest.tkvroh',
                'route_identifier_name' => 'tkvroh_id',
                'is_collection' => true,
            ],
        ],
    ],
];
