<?php
return [
    'service_manager' => [
        'factories' => [
            \Contabilidad\V1\Rest\Tbacpa\TbacpaResource::class => \Contabilidad\V1\Rest\Tbacpa\TbacpaResourceFactory::class,
            \Contabilidad\V1\Rest\Tbasad\TbasadResource::class => \Contabilidad\V1\Rest\Tbasad\TbasadResourceFactory::class,
            \Contabilidad\V1\Rest\Tbasah\TbasahResource::class => \Contabilidad\V1\Rest\Tbasah\TbasahResourceFactory::class,
            \Contabilidad\V1\Rest\Tbasrd\TbasrdResource::class => \Contabilidad\V1\Rest\Tbasrd\TbasrdResourceFactory::class,
            \Contabilidad\V1\Rest\Tbasrh\TbasrhResource::class => \Contabilidad\V1\Rest\Tbasrh\TbasrhResourceFactory::class,
            \Contabilidad\V1\Rest\Tbauxi\TbauxiResource::class => \Contabilidad\V1\Rest\Tbauxi\TbauxiResourceFactory::class,
            \Contabilidad\V1\Rest\Tbbcod\TbbcodResource::class => \Contabilidad\V1\Rest\Tbbcod\TbbcodResourceFactory::class,
            \Contabilidad\V1\Rest\Tbbcoh\TbbcohResource::class => \Contabilidad\V1\Rest\Tbbcoh\TbbcohResourceFactory::class,
            \Contabilidad\V1\Rest\Tbbcom\TbbcomResource::class => \Contabilidad\V1\Rest\Tbbcom\TbbcomResourceFactory::class,
            \Contabilidad\V1\Rest\Tbbcos\TbbcosResource::class => \Contabilidad\V1\Rest\Tbbcos\TbbcosResourceFactory::class,
            \Contabilidad\V1\Rest\Tbcatc\TbcatcResource::class => \Contabilidad\V1\Rest\Tbcatc\TbcatcResourceFactory::class,
            \Contabilidad\V1\Rest\Tbccon\TbcconResource::class => \Contabilidad\V1\Rest\Tbccon\TbcconResourceFactory::class,
            \Contabilidad\V1\Rest\Tbceco\TbcecoResource::class => \Contabilidad\V1\Rest\Tbceco\TbcecoResourceFactory::class,
            \Contabilidad\V1\Rest\Tbcote\TbcoteResource::class => \Contabilidad\V1\Rest\Tbcote\TbcoteResourceFactory::class,
            \Contabilidad\V1\Rest\Tbdncc\TbdnccResource::class => \Contabilidad\V1\Rest\Tbdncc\TbdnccResourceFactory::class,
            \Contabilidad\V1\Rest\Ttbecoc\TtbecocResource::class => \Contabilidad\V1\Rest\Ttbecoc\TtbecocResourceFactory::class,
            \Contabilidad\V1\Rest\Tbefdc\TbefdcResource::class => \Contabilidad\V1\Rest\Tbefdc\TbefdcResourceFactory::class,
            \Contabilidad\V1\Rest\Tbefdf\TbefdfResource::class => \Contabilidad\V1\Rest\Tbefdf\TbefdfResourceFactory::class,
            \Contabilidad\V1\Rest\Tbefin\TbefinResource::class => \Contabilidad\V1\Rest\Tbefin\TbefinResourceFactory::class,
            \Contabilidad\V1\Rest\Tbenco\TbencoResource::class => \Contabilidad\V1\Rest\Tbenco\TbencoResourceFactory::class,
            \Contabilidad\V1\Rest\Tbmone\TbmoneResource::class => \Contabilidad\V1\Rest\Tbmone\TbmoneResourceFactory::class,
            \Contabilidad\V1\Rest\Tbperc\TbpercResource::class => \Contabilidad\V1\Rest\Tbperc\TbpercResourceFactory::class,
            \Contabilidad\V1\Rest\Tbrlec\TbrlecResource::class => \Contabilidad\V1\Rest\Tbrlec\TbrlecResourceFactory::class,
            \Contabilidad\V1\Rest\Tbtiac\TbtiacResource::class => \Contabilidad\V1\Rest\Tbtiac\TbtiacResourceFactory::class,
            \Contabilidad\V1\Rest\Tbtias\TbtiasResource::class => \Contabilidad\V1\Rest\Tbtias\TbtiasResourceFactory::class,
            \Contabilidad\V1\Rest\Tbtiau\TbtiauResource::class => \Contabilidad\V1\Rest\Tbtiau\TbtiauResourceFactory::class,
            \Contabilidad\V1\Rest\Tbtica\TbticaResource::class => \Contabilidad\V1\Rest\Tbtica\TbticaResourceFactory::class,
            \Contabilidad\V1\Rest\Tbtido\TbtidoResource::class => \Contabilidad\V1\Rest\Tbtido\TbtidoResourceFactory::class,
            \Contabilidad\V1\Rest\Tbtiga\TbtigaResource::class => \Contabilidad\V1\Rest\Tbtiga\TbtigaResourceFactory::class,
            \Contabilidad\V1\Rest\Tbtipc\TbtipcResource::class => \Contabilidad\V1\Rest\Tbtipc\TbtipcResourceFactory::class,
        ],
    ],
    'router' => [
        'routes' => [
            'contabilidad.rest.tbacpa' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tbacpa[/:tbacpa_id]',
                    'defaults' => [
                        'controller' => 'Contabilidad\\V1\\Rest\\Tbacpa\\Controller',
                    ],
                ],
            ],
            'contabilidad.rest.tbasad' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tbasad[/:tbasad_id]',
                    'defaults' => [
                        'controller' => 'Contabilidad\\V1\\Rest\\Tbasad\\Controller',
                    ],
                ],
            ],
            'contabilidad.rest.tbasah' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tbasah[/:tbasah_id]',
                    'defaults' => [
                        'controller' => 'Contabilidad\\V1\\Rest\\Tbasah\\Controller',
                    ],
                ],
            ],
            'contabilidad.rest.tbasrd' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tbasrd[/:tbasrd_id]',
                    'defaults' => [
                        'controller' => 'Contabilidad\\V1\\Rest\\Tbasrd\\Controller',
                    ],
                ],
            ],
            'contabilidad.rest.tbasrh' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tbasrh[/:tbasrh_id]',
                    'defaults' => [
                        'controller' => 'Contabilidad\\V1\\Rest\\Tbasrh\\Controller',
                    ],
                ],
            ],
            'contabilidad.rest.tbauxi' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tbauxi[/:tbauxi_id]',
                    'defaults' => [
                        'controller' => 'Contabilidad\\V1\\Rest\\Tbauxi\\Controller',
                    ],
                ],
            ],
            'contabilidad.rest.tbbcod' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tbbcod[/:tbbcod_id]',
                    'defaults' => [
                        'controller' => 'Contabilidad\\V1\\Rest\\Tbbcod\\Controller',
                    ],
                ],
            ],
            'contabilidad.rest.tbbcoh' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tbbcoh[/:tbbcoh_id]',
                    'defaults' => [
                        'controller' => 'Contabilidad\\V1\\Rest\\Tbbcoh\\Controller',
                    ],
                ],
            ],
            'contabilidad.rest.tbbcom' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tbbcom[/:tbbcom_id]',
                    'defaults' => [
                        'controller' => 'Contabilidad\\V1\\Rest\\Tbbcom\\Controller',
                    ],
                ],
            ],
            'contabilidad.rest.tbbcos' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tbbcos[/:tbbcos_id]',
                    'defaults' => [
                        'controller' => 'Contabilidad\\V1\\Rest\\Tbbcos\\Controller',
                    ],
                ],
            ],
            'contabilidad.rest.tbcatc' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tbcatc[/:tbcatc_id]',
                    'defaults' => [
                        'controller' => 'Contabilidad\\V1\\Rest\\Tbcatc\\Controller',
                    ],
                ],
            ],
            'contabilidad.rest.tbccon' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tbccon[/:tbccon_id]',
                    'defaults' => [
                        'controller' => 'Contabilidad\\V1\\Rest\\Tbccon\\Controller',
                    ],
                ],
            ],
            'contabilidad.rest.tbceco' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tbceco[/:tbceco_id]',
                    'defaults' => [
                        'controller' => 'Contabilidad\\V1\\Rest\\Tbceco\\Controller',
                    ],
                ],
            ],
            'contabilidad.rest.tbcote' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tbcote[/:tbcote_id]',
                    'defaults' => [
                        'controller' => 'Contabilidad\\V1\\Rest\\Tbcote\\Controller',
                    ],
                ],
            ],
            'contabilidad.rest.tbdncc' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tbdncc[/:tbdncc_id]',
                    'defaults' => [
                        'controller' => 'Contabilidad\\V1\\Rest\\Tbdncc\\Controller',
                    ],
                ],
            ],
            'contabilidad.rest.ttbecoc' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/ttbecoc[/:ttbecoc_id]',
                    'defaults' => [
                        'controller' => 'Contabilidad\\V1\\Rest\\Ttbecoc\\Controller',
                    ],
                ],
            ],
            'contabilidad.rest.tbefdc' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tbefdc[/:tbefdc_id]',
                    'defaults' => [
                        'controller' => 'Contabilidad\\V1\\Rest\\Tbefdc\\Controller',
                    ],
                ],
            ],
            'contabilidad.rest.tbefdf' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tbefdf[/:tbefdf_id]',
                    'defaults' => [
                        'controller' => 'Contabilidad\\V1\\Rest\\Tbefdf\\Controller',
                    ],
                ],
            ],
            'contabilidad.rest.tbefin' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tbefin[/:tbefin_id]',
                    'defaults' => [
                        'controller' => 'Contabilidad\\V1\\Rest\\Tbefin\\Controller',
                    ],
                ],
            ],
            'contabilidad.rest.tbenco' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tbenco[/:tbenco_id]',
                    'defaults' => [
                        'controller' => 'Contabilidad\\V1\\Rest\\Tbenco\\Controller',
                    ],
                ],
            ],
            'contabilidad.rest.tbmone' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tbmone[/:tbmone_id]',
                    'defaults' => [
                        'controller' => 'Contabilidad\\V1\\Rest\\Tbmone\\Controller',
                    ],
                ],
            ],
            'contabilidad.rest.tbperc' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tbperc[/:tbperc_id]',
                    'defaults' => [
                        'controller' => 'Contabilidad\\V1\\Rest\\Tbperc\\Controller',
                    ],
                ],
            ],
            'contabilidad.rest.tbrlec' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tbrlec[/:tbrlec_id]',
                    'defaults' => [
                        'controller' => 'Contabilidad\\V1\\Rest\\Tbrlec\\Controller',
                    ],
                ],
            ],
            'contabilidad.rest.tbtiac' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tbtiac[/:tbtiac_id]',
                    'defaults' => [
                        'controller' => 'Contabilidad\\V1\\Rest\\Tbtiac\\Controller',
                    ],
                ],
            ],
            'contabilidad.rest.tbtias' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tbtias[/:tbtias_id]',
                    'defaults' => [
                        'controller' => 'Contabilidad\\V1\\Rest\\Tbtias\\Controller',
                    ],
                ],
            ],
            'contabilidad.rest.tbtiau' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tbtiau[/:tbtiau_id]',
                    'defaults' => [
                        'controller' => 'Contabilidad\\V1\\Rest\\Tbtiau\\Controller',
                    ],
                ],
            ],
            'contabilidad.rest.tbtica' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tbtica[/:tbtica_id]',
                    'defaults' => [
                        'controller' => 'Contabilidad\\V1\\Rest\\Tbtica\\Controller',
                    ],
                ],
            ],
            'contabilidad.rest.tbtido' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tbtido[/:tbtido_id]',
                    'defaults' => [
                        'controller' => 'Contabilidad\\V1\\Rest\\Tbtido\\Controller',
                    ],
                ],
            ],
            'contabilidad.rest.tbtiga' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tbtiga[/:tbtiga_id]',
                    'defaults' => [
                        'controller' => 'Contabilidad\\V1\\Rest\\Tbtiga\\Controller',
                    ],
                ],
            ],
            'contabilidad.rest.tbtipc' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tbtipc[/:tbtipc_id]',
                    'defaults' => [
                        'controller' => 'Contabilidad\\V1\\Rest\\Tbtipc\\Controller',
                    ],
                ],
            ],
        ],
    ],
    'zf-versioning' => [
        'uri' => [
            0 => 'contabilidad.rest.tbacpa',
            1 => 'contabilidad.rest.tbasad',
            2 => 'contabilidad.rest.tbasah',
            3 => 'contabilidad.rest.tbasrd',
            4 => 'contabilidad.rest.tbasrh',
            5 => 'contabilidad.rest.tbauxi',
            6 => 'contabilidad.rest.tbbcod',
            7 => 'contabilidad.rest.tbbcoh',
            8 => 'contabilidad.rest.tbbcom',
            9 => 'contabilidad.rest.tbbcos',
            10 => 'contabilidad.rest.tbcatc',
            11 => 'contabilidad.rest.tbccon',
            12 => 'contabilidad.rest.tbceco',
            13 => 'contabilidad.rest.tbcote',
            14 => 'contabilidad.rest.tbdncc',
            15 => 'contabilidad.rest.ttbecoc',
            16 => 'contabilidad.rest.tbefdc',
            17 => 'contabilidad.rest.tbefdf',
            18 => 'contabilidad.rest.tbefin',
            19 => 'contabilidad.rest.tbenco',
            20 => 'contabilidad.rest.tbmone',
            21 => 'contabilidad.rest.tbperc',
            22 => 'contabilidad.rest.tbrlec',
            23 => 'contabilidad.rest.tbtiac',
            24 => 'contabilidad.rest.tbtias',
            25 => 'contabilidad.rest.tbtiau',
            26 => 'contabilidad.rest.tbtica',
            27 => 'contabilidad.rest.tbtido',
            28 => 'contabilidad.rest.tbtiga',
            29 => 'contabilidad.rest.tbtipc',
        ],
    ],
    'zf-rest' => [
        'Contabilidad\\V1\\Rest\\Tbacpa\\Controller' => [
            'listener' => \Contabilidad\V1\Rest\Tbacpa\TbacpaResource::class,
            'route_name' => 'contabilidad.rest.tbacpa',
            'route_identifier_name' => 'tbacpa_id',
            'collection_name' => 'tbacpa',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Contabilidad\V1\Rest\Tbacpa\TbacpaEntity::class,
            'collection_class' => \Contabilidad\V1\Rest\Tbacpa\TbacpaCollection::class,
            'service_name' => 'Tbacpa',
        ],
        'Contabilidad\\V1\\Rest\\Tbasad\\Controller' => [
            'listener' => \Contabilidad\V1\Rest\Tbasad\TbasadResource::class,
            'route_name' => 'contabilidad.rest.tbasad',
            'route_identifier_name' => 'tbasad_id',
            'collection_name' => 'tbasad',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Contabilidad\V1\Rest\Tbasad\TbasadEntity::class,
            'collection_class' => \Contabilidad\V1\Rest\Tbasad\TbasadCollection::class,
            'service_name' => 'Tbasad',
        ],
        'Contabilidad\\V1\\Rest\\Tbasah\\Controller' => [
            'listener' => \Contabilidad\V1\Rest\Tbasah\TbasahResource::class,
            'route_name' => 'contabilidad.rest.tbasah',
            'route_identifier_name' => 'tbasah_id',
            'collection_name' => 'tbasah',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Contabilidad\V1\Rest\Tbasah\TbasahEntity::class,
            'collection_class' => \Contabilidad\V1\Rest\Tbasah\TbasahCollection::class,
            'service_name' => 'Tbasah',
        ],
        'Contabilidad\\V1\\Rest\\Tbasrd\\Controller' => [
            'listener' => \Contabilidad\V1\Rest\Tbasrd\TbasrdResource::class,
            'route_name' => 'contabilidad.rest.tbasrd',
            'route_identifier_name' => 'tbasrd_id',
            'collection_name' => 'tbasrd',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Contabilidad\V1\Rest\Tbasrd\TbasrdEntity::class,
            'collection_class' => \Contabilidad\V1\Rest\Tbasrd\TbasrdCollection::class,
            'service_name' => 'Tbasrd',
        ],
        'Contabilidad\\V1\\Rest\\Tbasrh\\Controller' => [
            'listener' => \Contabilidad\V1\Rest\Tbasrh\TbasrhResource::class,
            'route_name' => 'contabilidad.rest.tbasrh',
            'route_identifier_name' => 'tbasrh_id',
            'collection_name' => 'tbasrh',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Contabilidad\V1\Rest\Tbasrh\TbasrhEntity::class,
            'collection_class' => \Contabilidad\V1\Rest\Tbasrh\TbasrhCollection::class,
            'service_name' => 'Tbasrh',
        ],
        'Contabilidad\\V1\\Rest\\Tbauxi\\Controller' => [
            'listener' => \Contabilidad\V1\Rest\Tbauxi\TbauxiResource::class,
            'route_name' => 'contabilidad.rest.tbauxi',
            'route_identifier_name' => 'tbauxi_id',
            'collection_name' => 'tbauxi',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Contabilidad\V1\Rest\Tbauxi\TbauxiEntity::class,
            'collection_class' => \Contabilidad\V1\Rest\Tbauxi\TbauxiCollection::class,
            'service_name' => 'Tbauxi',
        ],
        'Contabilidad\\V1\\Rest\\Tbbcod\\Controller' => [
            'listener' => \Contabilidad\V1\Rest\Tbbcod\TbbcodResource::class,
            'route_name' => 'contabilidad.rest.tbbcod',
            'route_identifier_name' => 'tbbcod_id',
            'collection_name' => 'tbbcod',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Contabilidad\V1\Rest\Tbbcod\TbbcodEntity::class,
            'collection_class' => \Contabilidad\V1\Rest\Tbbcod\TbbcodCollection::class,
            'service_name' => 'Tbbcod',
        ],
        'Contabilidad\\V1\\Rest\\Tbbcoh\\Controller' => [
            'listener' => \Contabilidad\V1\Rest\Tbbcoh\TbbcohResource::class,
            'route_name' => 'contabilidad.rest.tbbcoh',
            'route_identifier_name' => 'tbbcoh_id',
            'collection_name' => 'tbbcoh',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Contabilidad\V1\Rest\Tbbcoh\TbbcohEntity::class,
            'collection_class' => \Contabilidad\V1\Rest\Tbbcoh\TbbcohCollection::class,
            'service_name' => 'Tbbcoh',
        ],
        'Contabilidad\\V1\\Rest\\Tbbcom\\Controller' => [
            'listener' => \Contabilidad\V1\Rest\Tbbcom\TbbcomResource::class,
            'route_name' => 'contabilidad.rest.tbbcom',
            'route_identifier_name' => 'tbbcom_id',
            'collection_name' => 'tbbcom',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Contabilidad\V1\Rest\Tbbcom\TbbcomEntity::class,
            'collection_class' => \Contabilidad\V1\Rest\Tbbcom\TbbcomCollection::class,
            'service_name' => 'Tbbcom',
        ],
        'Contabilidad\\V1\\Rest\\Tbbcos\\Controller' => [
            'listener' => \Contabilidad\V1\Rest\Tbbcos\TbbcosResource::class,
            'route_name' => 'contabilidad.rest.tbbcos',
            'route_identifier_name' => 'tbbcos_id',
            'collection_name' => 'tbbcos',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Contabilidad\V1\Rest\Tbbcos\TbbcosEntity::class,
            'collection_class' => \Contabilidad\V1\Rest\Tbbcos\TbbcosCollection::class,
            'service_name' => 'Tbbcos',
        ],
        'Contabilidad\\V1\\Rest\\Tbcatc\\Controller' => [
            'listener' => \Contabilidad\V1\Rest\Tbcatc\TbcatcResource::class,
            'route_name' => 'contabilidad.rest.tbcatc',
            'route_identifier_name' => 'tbcatc_id',
            'collection_name' => 'tbcatc',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Contabilidad\V1\Rest\Tbcatc\TbcatcEntity::class,
            'collection_class' => \Contabilidad\V1\Rest\Tbcatc\TbcatcCollection::class,
            'service_name' => 'Tbcatc',
        ],
        'Contabilidad\\V1\\Rest\\Tbccon\\Controller' => [
            'listener' => \Contabilidad\V1\Rest\Tbccon\TbcconResource::class,
            'route_name' => 'contabilidad.rest.tbccon',
            'route_identifier_name' => 'tbccon_id',
            'collection_name' => 'tbccon',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Contabilidad\V1\Rest\Tbccon\TbcconEntity::class,
            'collection_class' => \Contabilidad\V1\Rest\Tbccon\TbcconCollection::class,
            'service_name' => 'Tbccon',
        ],
        'Contabilidad\\V1\\Rest\\Tbceco\\Controller' => [
            'listener' => \Contabilidad\V1\Rest\Tbceco\TbcecoResource::class,
            'route_name' => 'contabilidad.rest.tbceco',
            'route_identifier_name' => 'tbceco_id',
            'collection_name' => 'tbceco',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Contabilidad\V1\Rest\Tbceco\TbcecoEntity::class,
            'collection_class' => \Contabilidad\V1\Rest\Tbceco\TbcecoCollection::class,
            'service_name' => 'Tbceco',
        ],
        'Contabilidad\\V1\\Rest\\Tbcote\\Controller' => [
            'listener' => \Contabilidad\V1\Rest\Tbcote\TbcoteResource::class,
            'route_name' => 'contabilidad.rest.tbcote',
            'route_identifier_name' => 'tbcote_id',
            'collection_name' => 'tbcote',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Contabilidad\V1\Rest\Tbcote\TbcoteEntity::class,
            'collection_class' => \Contabilidad\V1\Rest\Tbcote\TbcoteCollection::class,
            'service_name' => 'Tbcote',
        ],
        'Contabilidad\\V1\\Rest\\Tbdncc\\Controller' => [
            'listener' => \Contabilidad\V1\Rest\Tbdncc\TbdnccResource::class,
            'route_name' => 'contabilidad.rest.tbdncc',
            'route_identifier_name' => 'tbdncc_id',
            'collection_name' => 'tbdncc',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Contabilidad\V1\Rest\Tbdncc\TbdnccEntity::class,
            'collection_class' => \Contabilidad\V1\Rest\Tbdncc\TbdnccCollection::class,
            'service_name' => 'Tbdncc',
        ],
        'Contabilidad\\V1\\Rest\\Ttbecoc\\Controller' => [
            'listener' => \Contabilidad\V1\Rest\Ttbecoc\TtbecocResource::class,
            'route_name' => 'contabilidad.rest.ttbecoc',
            'route_identifier_name' => 'ttbecoc_id',
            'collection_name' => 'ttbecoc',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Contabilidad\V1\Rest\Ttbecoc\TtbecocEntity::class,
            'collection_class' => \Contabilidad\V1\Rest\Ttbecoc\TtbecocCollection::class,
            'service_name' => 'Ttbecoc',
        ],
        'Contabilidad\\V1\\Rest\\Tbefdc\\Controller' => [
            'listener' => \Contabilidad\V1\Rest\Tbefdc\TbefdcResource::class,
            'route_name' => 'contabilidad.rest.tbefdc',
            'route_identifier_name' => 'tbefdc_id',
            'collection_name' => 'tbefdc',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Contabilidad\V1\Rest\Tbefdc\TbefdcEntity::class,
            'collection_class' => \Contabilidad\V1\Rest\Tbefdc\TbefdcCollection::class,
            'service_name' => 'Tbefdc',
        ],
        'Contabilidad\\V1\\Rest\\Tbefdf\\Controller' => [
            'listener' => \Contabilidad\V1\Rest\Tbefdf\TbefdfResource::class,
            'route_name' => 'contabilidad.rest.tbefdf',
            'route_identifier_name' => 'tbefdf_id',
            'collection_name' => 'tbefdf',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Contabilidad\V1\Rest\Tbefdf\TbefdfEntity::class,
            'collection_class' => \Contabilidad\V1\Rest\Tbefdf\TbefdfCollection::class,
            'service_name' => 'Tbefdf',
        ],
        'Contabilidad\\V1\\Rest\\Tbefin\\Controller' => [
            'listener' => \Contabilidad\V1\Rest\Tbefin\TbefinResource::class,
            'route_name' => 'contabilidad.rest.tbefin',
            'route_identifier_name' => 'tbefin_id',
            'collection_name' => 'tbefin',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Contabilidad\V1\Rest\Tbefin\TbefinEntity::class,
            'collection_class' => \Contabilidad\V1\Rest\Tbefin\TbefinCollection::class,
            'service_name' => 'Tbefin',
        ],
        'Contabilidad\\V1\\Rest\\Tbenco\\Controller' => [
            'listener' => \Contabilidad\V1\Rest\Tbenco\TbencoResource::class,
            'route_name' => 'contabilidad.rest.tbenco',
            'route_identifier_name' => 'tbenco_id',
            'collection_name' => 'tbenco',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Contabilidad\V1\Rest\Tbenco\TbencoEntity::class,
            'collection_class' => \Contabilidad\V1\Rest\Tbenco\TbencoCollection::class,
            'service_name' => 'Tbenco',
        ],
        'Contabilidad\\V1\\Rest\\Tbmone\\Controller' => [
            'listener' => \Contabilidad\V1\Rest\Tbmone\TbmoneResource::class,
            'route_name' => 'contabilidad.rest.tbmone',
            'route_identifier_name' => 'tbmone_id',
            'collection_name' => 'tbmone',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Contabilidad\V1\Rest\Tbmone\TbmoneEntity::class,
            'collection_class' => \Contabilidad\V1\Rest\Tbmone\TbmoneCollection::class,
            'service_name' => 'Tbmone',
        ],
        'Contabilidad\\V1\\Rest\\Tbperc\\Controller' => [
            'listener' => \Contabilidad\V1\Rest\Tbperc\TbpercResource::class,
            'route_name' => 'contabilidad.rest.tbperc',
            'route_identifier_name' => 'tbperc_id',
            'collection_name' => 'tbperc',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Contabilidad\V1\Rest\Tbperc\TbpercEntity::class,
            'collection_class' => \Contabilidad\V1\Rest\Tbperc\TbpercCollection::class,
            'service_name' => 'Tbperc',
        ],
        'Contabilidad\\V1\\Rest\\Tbrlec\\Controller' => [
            'listener' => \Contabilidad\V1\Rest\Tbrlec\TbrlecResource::class,
            'route_name' => 'contabilidad.rest.tbrlec',
            'route_identifier_name' => 'tbrlec_id',
            'collection_name' => 'tbrlec',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Contabilidad\V1\Rest\Tbrlec\TbrlecEntity::class,
            'collection_class' => \Contabilidad\V1\Rest\Tbrlec\TbrlecCollection::class,
            'service_name' => 'Tbrlec',
        ],
        'Contabilidad\\V1\\Rest\\Tbtiac\\Controller' => [
            'listener' => \Contabilidad\V1\Rest\Tbtiac\TbtiacResource::class,
            'route_name' => 'contabilidad.rest.tbtiac',
            'route_identifier_name' => 'tbtiac_id',
            'collection_name' => 'tbtiac',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Contabilidad\V1\Rest\Tbtiac\TbtiacEntity::class,
            'collection_class' => \Contabilidad\V1\Rest\Tbtiac\TbtiacCollection::class,
            'service_name' => 'Tbtiac',
        ],
        'Contabilidad\\V1\\Rest\\Tbtias\\Controller' => [
            'listener' => \Contabilidad\V1\Rest\Tbtias\TbtiasResource::class,
            'route_name' => 'contabilidad.rest.tbtias',
            'route_identifier_name' => 'tbtias_id',
            'collection_name' => 'tbtias',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Contabilidad\V1\Rest\Tbtias\TbtiasEntity::class,
            'collection_class' => \Contabilidad\V1\Rest\Tbtias\TbtiasCollection::class,
            'service_name' => 'Tbtias',
        ],
        'Contabilidad\\V1\\Rest\\Tbtiau\\Controller' => [
            'listener' => \Contabilidad\V1\Rest\Tbtiau\TbtiauResource::class,
            'route_name' => 'contabilidad.rest.tbtiau',
            'route_identifier_name' => 'tbtiau_id',
            'collection_name' => 'tbtiau',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Contabilidad\V1\Rest\Tbtiau\TbtiauEntity::class,
            'collection_class' => \Contabilidad\V1\Rest\Tbtiau\TbtiauCollection::class,
            'service_name' => 'Tbtiau',
        ],
        'Contabilidad\\V1\\Rest\\Tbtica\\Controller' => [
            'listener' => \Contabilidad\V1\Rest\Tbtica\TbticaResource::class,
            'route_name' => 'contabilidad.rest.tbtica',
            'route_identifier_name' => 'tbtica_id',
            'collection_name' => 'tbtica',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Contabilidad\V1\Rest\Tbtica\TbticaEntity::class,
            'collection_class' => \Contabilidad\V1\Rest\Tbtica\TbticaCollection::class,
            'service_name' => 'Tbtica',
        ],
        'Contabilidad\\V1\\Rest\\Tbtido\\Controller' => [
            'listener' => \Contabilidad\V1\Rest\Tbtido\TbtidoResource::class,
            'route_name' => 'contabilidad.rest.tbtido',
            'route_identifier_name' => 'tbtido_id',
            'collection_name' => 'tbtido',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Contabilidad\V1\Rest\Tbtido\TbtidoEntity::class,
            'collection_class' => \Contabilidad\V1\Rest\Tbtido\TbtidoCollection::class,
            'service_name' => 'Tbtido',
        ],
        'Contabilidad\\V1\\Rest\\Tbtiga\\Controller' => [
            'listener' => \Contabilidad\V1\Rest\Tbtiga\TbtigaResource::class,
            'route_name' => 'contabilidad.rest.tbtiga',
            'route_identifier_name' => 'tbtiga_id',
            'collection_name' => 'tbtiga',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Contabilidad\V1\Rest\Tbtiga\TbtigaEntity::class,
            'collection_class' => \Contabilidad\V1\Rest\Tbtiga\TbtigaCollection::class,
            'service_name' => 'Tbtiga',
        ],
        'Contabilidad\\V1\\Rest\\Tbtipc\\Controller' => [
            'listener' => \Contabilidad\V1\Rest\Tbtipc\TbtipcResource::class,
            'route_name' => 'contabilidad.rest.tbtipc',
            'route_identifier_name' => 'tbtipc_id',
            'collection_name' => 'tbtipc',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Contabilidad\V1\Rest\Tbtipc\TbtipcEntity::class,
            'collection_class' => \Contabilidad\V1\Rest\Tbtipc\TbtipcCollection::class,
            'service_name' => 'Tbtipc',
        ],
    ],
    'zf-content-negotiation' => [
        'controllers' => [
            'Contabilidad\\V1\\Rest\\Tbacpa\\Controller' => 'HalJson',
            'Contabilidad\\V1\\Rest\\Tbasad\\Controller' => 'HalJson',
            'Contabilidad\\V1\\Rest\\Tbasah\\Controller' => 'HalJson',
            'Contabilidad\\V1\\Rest\\Tbasrd\\Controller' => 'HalJson',
            'Contabilidad\\V1\\Rest\\Tbasrh\\Controller' => 'HalJson',
            'Contabilidad\\V1\\Rest\\Tbauxi\\Controller' => 'HalJson',
            'Contabilidad\\V1\\Rest\\Tbbcod\\Controller' => 'HalJson',
            'Contabilidad\\V1\\Rest\\Tbbcoh\\Controller' => 'HalJson',
            'Contabilidad\\V1\\Rest\\Tbbcom\\Controller' => 'HalJson',
            'Contabilidad\\V1\\Rest\\Tbbcos\\Controller' => 'HalJson',
            'Contabilidad\\V1\\Rest\\Tbcatc\\Controller' => 'HalJson',
            'Contabilidad\\V1\\Rest\\Tbccon\\Controller' => 'HalJson',
            'Contabilidad\\V1\\Rest\\Tbceco\\Controller' => 'HalJson',
            'Contabilidad\\V1\\Rest\\Tbcote\\Controller' => 'HalJson',
            'Contabilidad\\V1\\Rest\\Tbdncc\\Controller' => 'HalJson',
            'Contabilidad\\V1\\Rest\\Ttbecoc\\Controller' => 'HalJson',
            'Contabilidad\\V1\\Rest\\Tbefdc\\Controller' => 'HalJson',
            'Contabilidad\\V1\\Rest\\Tbefdf\\Controller' => 'HalJson',
            'Contabilidad\\V1\\Rest\\Tbefin\\Controller' => 'HalJson',
            'Contabilidad\\V1\\Rest\\Tbenco\\Controller' => 'HalJson',
            'Contabilidad\\V1\\Rest\\Tbmone\\Controller' => 'HalJson',
            'Contabilidad\\V1\\Rest\\Tbperc\\Controller' => 'HalJson',
            'Contabilidad\\V1\\Rest\\Tbrlec\\Controller' => 'HalJson',
            'Contabilidad\\V1\\Rest\\Tbtiac\\Controller' => 'HalJson',
            'Contabilidad\\V1\\Rest\\Tbtias\\Controller' => 'HalJson',
            'Contabilidad\\V1\\Rest\\Tbtiau\\Controller' => 'HalJson',
            'Contabilidad\\V1\\Rest\\Tbtica\\Controller' => 'HalJson',
            'Contabilidad\\V1\\Rest\\Tbtido\\Controller' => 'HalJson',
            'Contabilidad\\V1\\Rest\\Tbtiga\\Controller' => 'HalJson',
            'Contabilidad\\V1\\Rest\\Tbtipc\\Controller' => 'HalJson',
        ],
        'accept_whitelist' => [
            'Contabilidad\\V1\\Rest\\Tbacpa\\Controller' => [
                0 => 'application/vnd.contabilidad.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Contabilidad\\V1\\Rest\\Tbasad\\Controller' => [
                0 => 'application/vnd.contabilidad.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Contabilidad\\V1\\Rest\\Tbasah\\Controller' => [
                0 => 'application/vnd.contabilidad.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Contabilidad\\V1\\Rest\\Tbasrd\\Controller' => [
                0 => 'application/vnd.contabilidad.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Contabilidad\\V1\\Rest\\Tbasrh\\Controller' => [
                0 => 'application/vnd.contabilidad.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Contabilidad\\V1\\Rest\\Tbauxi\\Controller' => [
                0 => 'application/vnd.contabilidad.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Contabilidad\\V1\\Rest\\Tbbcod\\Controller' => [
                0 => 'application/vnd.contabilidad.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Contabilidad\\V1\\Rest\\Tbbcoh\\Controller' => [
                0 => 'application/vnd.contabilidad.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Contabilidad\\V1\\Rest\\Tbbcom\\Controller' => [
                0 => 'application/vnd.contabilidad.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Contabilidad\\V1\\Rest\\Tbbcos\\Controller' => [
                0 => 'application/vnd.contabilidad.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Contabilidad\\V1\\Rest\\Tbcatc\\Controller' => [
                0 => 'application/vnd.contabilidad.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Contabilidad\\V1\\Rest\\Tbccon\\Controller' => [
                0 => 'application/vnd.contabilidad.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Contabilidad\\V1\\Rest\\Tbceco\\Controller' => [
                0 => 'application/vnd.contabilidad.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Contabilidad\\V1\\Rest\\Tbcote\\Controller' => [
                0 => 'application/vnd.contabilidad.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Contabilidad\\V1\\Rest\\Tbdncc\\Controller' => [
                0 => 'application/vnd.contabilidad.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Contabilidad\\V1\\Rest\\Ttbecoc\\Controller' => [
                0 => 'application/vnd.contabilidad.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Contabilidad\\V1\\Rest\\Tbefdc\\Controller' => [
                0 => 'application/vnd.contabilidad.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Contabilidad\\V1\\Rest\\Tbefdf\\Controller' => [
                0 => 'application/vnd.contabilidad.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Contabilidad\\V1\\Rest\\Tbefin\\Controller' => [
                0 => 'application/vnd.contabilidad.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Contabilidad\\V1\\Rest\\Tbenco\\Controller' => [
                0 => 'application/vnd.contabilidad.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Contabilidad\\V1\\Rest\\Tbmone\\Controller' => [
                0 => 'application/vnd.contabilidad.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Contabilidad\\V1\\Rest\\Tbperc\\Controller' => [
                0 => 'application/vnd.contabilidad.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Contabilidad\\V1\\Rest\\Tbrlec\\Controller' => [
                0 => 'application/vnd.contabilidad.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Contabilidad\\V1\\Rest\\Tbtiac\\Controller' => [
                0 => 'application/vnd.contabilidad.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Contabilidad\\V1\\Rest\\Tbtias\\Controller' => [
                0 => 'application/vnd.contabilidad.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Contabilidad\\V1\\Rest\\Tbtiau\\Controller' => [
                0 => 'application/vnd.contabilidad.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Contabilidad\\V1\\Rest\\Tbtica\\Controller' => [
                0 => 'application/vnd.contabilidad.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Contabilidad\\V1\\Rest\\Tbtido\\Controller' => [
                0 => 'application/vnd.contabilidad.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Contabilidad\\V1\\Rest\\Tbtiga\\Controller' => [
                0 => 'application/vnd.contabilidad.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Contabilidad\\V1\\Rest\\Tbtipc\\Controller' => [
                0 => 'application/vnd.contabilidad.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
        ],
        'content_type_whitelist' => [
            'Contabilidad\\V1\\Rest\\Tbacpa\\Controller' => [
                0 => 'application/vnd.contabilidad.v1+json',
                1 => 'application/json',
            ],
            'Contabilidad\\V1\\Rest\\Tbasad\\Controller' => [
                0 => 'application/vnd.contabilidad.v1+json',
                1 => 'application/json',
            ],
            'Contabilidad\\V1\\Rest\\Tbasah\\Controller' => [
                0 => 'application/vnd.contabilidad.v1+json',
                1 => 'application/json',
            ],
            'Contabilidad\\V1\\Rest\\Tbasrd\\Controller' => [
                0 => 'application/vnd.contabilidad.v1+json',
                1 => 'application/json',
            ],
            'Contabilidad\\V1\\Rest\\Tbasrh\\Controller' => [
                0 => 'application/vnd.contabilidad.v1+json',
                1 => 'application/json',
            ],
            'Contabilidad\\V1\\Rest\\Tbauxi\\Controller' => [
                0 => 'application/vnd.contabilidad.v1+json',
                1 => 'application/json',
            ],
            'Contabilidad\\V1\\Rest\\Tbbcod\\Controller' => [
                0 => 'application/vnd.contabilidad.v1+json',
                1 => 'application/json',
            ],
            'Contabilidad\\V1\\Rest\\Tbbcoh\\Controller' => [
                0 => 'application/vnd.contabilidad.v1+json',
                1 => 'application/json',
            ],
            'Contabilidad\\V1\\Rest\\Tbbcom\\Controller' => [
                0 => 'application/vnd.contabilidad.v1+json',
                1 => 'application/json',
            ],
            'Contabilidad\\V1\\Rest\\Tbbcos\\Controller' => [
                0 => 'application/vnd.contabilidad.v1+json',
                1 => 'application/json',
            ],
            'Contabilidad\\V1\\Rest\\Tbcatc\\Controller' => [
                0 => 'application/vnd.contabilidad.v1+json',
                1 => 'application/json',
            ],
            'Contabilidad\\V1\\Rest\\Tbccon\\Controller' => [
                0 => 'application/vnd.contabilidad.v1+json',
                1 => 'application/json',
            ],
            'Contabilidad\\V1\\Rest\\Tbceco\\Controller' => [
                0 => 'application/vnd.contabilidad.v1+json',
                1 => 'application/json',
            ],
            'Contabilidad\\V1\\Rest\\Tbcote\\Controller' => [
                0 => 'application/vnd.contabilidad.v1+json',
                1 => 'application/json',
            ],
            'Contabilidad\\V1\\Rest\\Tbdncc\\Controller' => [
                0 => 'application/vnd.contabilidad.v1+json',
                1 => 'application/json',
            ],
            'Contabilidad\\V1\\Rest\\Ttbecoc\\Controller' => [
                0 => 'application/vnd.contabilidad.v1+json',
                1 => 'application/json',
            ],
            'Contabilidad\\V1\\Rest\\Tbefdc\\Controller' => [
                0 => 'application/vnd.contabilidad.v1+json',
                1 => 'application/json',
            ],
            'Contabilidad\\V1\\Rest\\Tbefdf\\Controller' => [
                0 => 'application/vnd.contabilidad.v1+json',
                1 => 'application/json',
            ],
            'Contabilidad\\V1\\Rest\\Tbefin\\Controller' => [
                0 => 'application/vnd.contabilidad.v1+json',
                1 => 'application/json',
            ],
            'Contabilidad\\V1\\Rest\\Tbenco\\Controller' => [
                0 => 'application/vnd.contabilidad.v1+json',
                1 => 'application/json',
            ],
            'Contabilidad\\V1\\Rest\\Tbmone\\Controller' => [
                0 => 'application/vnd.contabilidad.v1+json',
                1 => 'application/json',
            ],
            'Contabilidad\\V1\\Rest\\Tbperc\\Controller' => [
                0 => 'application/vnd.contabilidad.v1+json',
                1 => 'application/json',
            ],
            'Contabilidad\\V1\\Rest\\Tbrlec\\Controller' => [
                0 => 'application/vnd.contabilidad.v1+json',
                1 => 'application/json',
            ],
            'Contabilidad\\V1\\Rest\\Tbtiac\\Controller' => [
                0 => 'application/vnd.contabilidad.v1+json',
                1 => 'application/json',
            ],
            'Contabilidad\\V1\\Rest\\Tbtias\\Controller' => [
                0 => 'application/vnd.contabilidad.v1+json',
                1 => 'application/json',
            ],
            'Contabilidad\\V1\\Rest\\Tbtiau\\Controller' => [
                0 => 'application/vnd.contabilidad.v1+json',
                1 => 'application/json',
            ],
            'Contabilidad\\V1\\Rest\\Tbtica\\Controller' => [
                0 => 'application/vnd.contabilidad.v1+json',
                1 => 'application/json',
            ],
            'Contabilidad\\V1\\Rest\\Tbtido\\Controller' => [
                0 => 'application/vnd.contabilidad.v1+json',
                1 => 'application/json',
            ],
            'Contabilidad\\V1\\Rest\\Tbtiga\\Controller' => [
                0 => 'application/vnd.contabilidad.v1+json',
                1 => 'application/json',
            ],
            'Contabilidad\\V1\\Rest\\Tbtipc\\Controller' => [
                0 => 'application/vnd.contabilidad.v1+json',
                1 => 'application/json',
            ],
        ],
    ],
    'zf-hal' => [
        'metadata_map' => [
            \Contabilidad\V1\Rest\Tbacpa\TbacpaEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'contabilidad.rest.tbacpa',
                'route_identifier_name' => 'tbacpa_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Contabilidad\V1\Rest\Tbacpa\TbacpaCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'contabilidad.rest.tbacpa',
                'route_identifier_name' => 'tbacpa_id',
                'is_collection' => true,
            ],
            \Contabilidad\V1\Rest\Tbasad\TbasadEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'contabilidad.rest.tbasad',
                'route_identifier_name' => 'tbasad_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Contabilidad\V1\Rest\Tbasad\TbasadCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'contabilidad.rest.tbasad',
                'route_identifier_name' => 'tbasad_id',
                'is_collection' => true,
            ],
            \Contabilidad\V1\Rest\Tbasah\TbasahEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'contabilidad.rest.tbasah',
                'route_identifier_name' => 'tbasah_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Contabilidad\V1\Rest\Tbasah\TbasahCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'contabilidad.rest.tbasah',
                'route_identifier_name' => 'tbasah_id',
                'is_collection' => true,
            ],
            \Contabilidad\V1\Rest\Tbasrd\TbasrdEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'contabilidad.rest.tbasrd',
                'route_identifier_name' => 'tbasrd_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Contabilidad\V1\Rest\Tbasrd\TbasrdCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'contabilidad.rest.tbasrd',
                'route_identifier_name' => 'tbasrd_id',
                'is_collection' => true,
            ],
            \Contabilidad\V1\Rest\Tbasrh\TbasrhEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'contabilidad.rest.tbasrh',
                'route_identifier_name' => 'tbasrh_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Contabilidad\V1\Rest\Tbasrh\TbasrhCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'contabilidad.rest.tbasrh',
                'route_identifier_name' => 'tbasrh_id',
                'is_collection' => true,
            ],
            \Contabilidad\V1\Rest\Tbauxi\TbauxiEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'contabilidad.rest.tbauxi',
                'route_identifier_name' => 'tbauxi_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Contabilidad\V1\Rest\Tbauxi\TbauxiCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'contabilidad.rest.tbauxi',
                'route_identifier_name' => 'tbauxi_id',
                'is_collection' => true,
            ],
            \Contabilidad\V1\Rest\Tbbcod\TbbcodEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'contabilidad.rest.tbbcod',
                'route_identifier_name' => 'tbbcod_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Contabilidad\V1\Rest\Tbbcod\TbbcodCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'contabilidad.rest.tbbcod',
                'route_identifier_name' => 'tbbcod_id',
                'is_collection' => true,
            ],
            \Contabilidad\V1\Rest\Tbbcoh\TbbcohEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'contabilidad.rest.tbbcoh',
                'route_identifier_name' => 'tbbcoh_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Contabilidad\V1\Rest\Tbbcoh\TbbcohCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'contabilidad.rest.tbbcoh',
                'route_identifier_name' => 'tbbcoh_id',
                'is_collection' => true,
            ],
            \Contabilidad\V1\Rest\Tbbcom\TbbcomEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'contabilidad.rest.tbbcom',
                'route_identifier_name' => 'tbbcom_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Contabilidad\V1\Rest\Tbbcom\TbbcomCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'contabilidad.rest.tbbcom',
                'route_identifier_name' => 'tbbcom_id',
                'is_collection' => true,
            ],
            \Contabilidad\V1\Rest\Tbbcos\TbbcosEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'contabilidad.rest.tbbcos',
                'route_identifier_name' => 'tbbcos_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Contabilidad\V1\Rest\Tbbcos\TbbcosCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'contabilidad.rest.tbbcos',
                'route_identifier_name' => 'tbbcos_id',
                'is_collection' => true,
            ],
            \Contabilidad\V1\Rest\Tbcatc\TbcatcEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'contabilidad.rest.tbcatc',
                'route_identifier_name' => 'tbcatc_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Contabilidad\V1\Rest\Tbcatc\TbcatcCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'contabilidad.rest.tbcatc',
                'route_identifier_name' => 'tbcatc_id',
                'is_collection' => true,
            ],
            \Contabilidad\V1\Rest\Tbccon\TbcconEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'contabilidad.rest.tbccon',
                'route_identifier_name' => 'tbccon_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Contabilidad\V1\Rest\Tbccon\TbcconCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'contabilidad.rest.tbccon',
                'route_identifier_name' => 'tbccon_id',
                'is_collection' => true,
            ],
            \Contabilidad\V1\Rest\Tbceco\TbcecoEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'contabilidad.rest.tbceco',
                'route_identifier_name' => 'tbceco_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Contabilidad\V1\Rest\Tbceco\TbcecoCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'contabilidad.rest.tbceco',
                'route_identifier_name' => 'tbceco_id',
                'is_collection' => true,
            ],
            \Contabilidad\V1\Rest\Tbcote\TbcoteEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'contabilidad.rest.tbcote',
                'route_identifier_name' => 'tbcote_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Contabilidad\V1\Rest\Tbcote\TbcoteCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'contabilidad.rest.tbcote',
                'route_identifier_name' => 'tbcote_id',
                'is_collection' => true,
            ],
            \Contabilidad\V1\Rest\Tbdncc\TbdnccEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'contabilidad.rest.tbdncc',
                'route_identifier_name' => 'tbdncc_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Contabilidad\V1\Rest\Tbdncc\TbdnccCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'contabilidad.rest.tbdncc',
                'route_identifier_name' => 'tbdncc_id',
                'is_collection' => true,
            ],
            \Contabilidad\V1\Rest\Ttbecoc\TtbecocEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'contabilidad.rest.ttbecoc',
                'route_identifier_name' => 'ttbecoc_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Contabilidad\V1\Rest\Ttbecoc\TtbecocCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'contabilidad.rest.ttbecoc',
                'route_identifier_name' => 'ttbecoc_id',
                'is_collection' => true,
            ],
            \Contabilidad\V1\Rest\Tbefdc\TbefdcEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'contabilidad.rest.tbefdc',
                'route_identifier_name' => 'tbefdc_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Contabilidad\V1\Rest\Tbefdc\TbefdcCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'contabilidad.rest.tbefdc',
                'route_identifier_name' => 'tbefdc_id',
                'is_collection' => true,
            ],
            \Contabilidad\V1\Rest\Tbefdf\TbefdfEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'contabilidad.rest.tbefdf',
                'route_identifier_name' => 'tbefdf_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Contabilidad\V1\Rest\Tbefdf\TbefdfCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'contabilidad.rest.tbefdf',
                'route_identifier_name' => 'tbefdf_id',
                'is_collection' => true,
            ],
            \Contabilidad\V1\Rest\Tbefin\TbefinEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'contabilidad.rest.tbefin',
                'route_identifier_name' => 'tbefin_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Contabilidad\V1\Rest\Tbefin\TbefinCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'contabilidad.rest.tbefin',
                'route_identifier_name' => 'tbefin_id',
                'is_collection' => true,
            ],
            \Contabilidad\V1\Rest\Tbenco\TbencoEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'contabilidad.rest.tbenco',
                'route_identifier_name' => 'tbenco_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Contabilidad\V1\Rest\Tbenco\TbencoCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'contabilidad.rest.tbenco',
                'route_identifier_name' => 'tbenco_id',
                'is_collection' => true,
            ],
            \Contabilidad\V1\Rest\Tbmone\TbmoneEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'contabilidad.rest.tbmone',
                'route_identifier_name' => 'tbmone_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Contabilidad\V1\Rest\Tbmone\TbmoneCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'contabilidad.rest.tbmone',
                'route_identifier_name' => 'tbmone_id',
                'is_collection' => true,
            ],
            \Contabilidad\V1\Rest\Tbperc\TbpercEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'contabilidad.rest.tbperc',
                'route_identifier_name' => 'tbperc_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Contabilidad\V1\Rest\Tbperc\TbpercCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'contabilidad.rest.tbperc',
                'route_identifier_name' => 'tbperc_id',
                'is_collection' => true,
            ],
            \Contabilidad\V1\Rest\Tbrlec\TbrlecEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'contabilidad.rest.tbrlec',
                'route_identifier_name' => 'tbrlec_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Contabilidad\V1\Rest\Tbrlec\TbrlecCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'contabilidad.rest.tbrlec',
                'route_identifier_name' => 'tbrlec_id',
                'is_collection' => true,
            ],
            \Contabilidad\V1\Rest\Tbtiac\TbtiacEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'contabilidad.rest.tbtiac',
                'route_identifier_name' => 'tbtiac_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Contabilidad\V1\Rest\Tbtiac\TbtiacCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'contabilidad.rest.tbtiac',
                'route_identifier_name' => 'tbtiac_id',
                'is_collection' => true,
            ],
            \Contabilidad\V1\Rest\Tbtias\TbtiasEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'contabilidad.rest.tbtias',
                'route_identifier_name' => 'tbtias_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Contabilidad\V1\Rest\Tbtias\TbtiasCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'contabilidad.rest.tbtias',
                'route_identifier_name' => 'tbtias_id',
                'is_collection' => true,
            ],
            \Contabilidad\V1\Rest\Tbtiau\TbtiauEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'contabilidad.rest.tbtiau',
                'route_identifier_name' => 'tbtiau_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Contabilidad\V1\Rest\Tbtiau\TbtiauCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'contabilidad.rest.tbtiau',
                'route_identifier_name' => 'tbtiau_id',
                'is_collection' => true,
            ],
            \Contabilidad\V1\Rest\Tbtica\TbticaEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'contabilidad.rest.tbtica',
                'route_identifier_name' => 'tbtica_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Contabilidad\V1\Rest\Tbtica\TbticaCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'contabilidad.rest.tbtica',
                'route_identifier_name' => 'tbtica_id',
                'is_collection' => true,
            ],
            \Contabilidad\V1\Rest\Tbtido\TbtidoEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'contabilidad.rest.tbtido',
                'route_identifier_name' => 'tbtido_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Contabilidad\V1\Rest\Tbtido\TbtidoCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'contabilidad.rest.tbtido',
                'route_identifier_name' => 'tbtido_id',
                'is_collection' => true,
            ],
            \Contabilidad\V1\Rest\Tbtiga\TbtigaEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'contabilidad.rest.tbtiga',
                'route_identifier_name' => 'tbtiga_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Contabilidad\V1\Rest\Tbtiga\TbtigaCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'contabilidad.rest.tbtiga',
                'route_identifier_name' => 'tbtiga_id',
                'is_collection' => true,
            ],
            \Contabilidad\V1\Rest\Tbtipc\TbtipcEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'contabilidad.rest.tbtipc',
                'route_identifier_name' => 'tbtipc_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Contabilidad\V1\Rest\Tbtipc\TbtipcCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'contabilidad.rest.tbtipc',
                'route_identifier_name' => 'tbtipc_id',
                'is_collection' => true,
            ],
        ],
    ],
];
