<?php
return [
    'service_manager' => [
        'aliases' => [
            \Inventario\Repository\ITkrecdRepository::class => \Inventario\Repository\Impl\TkrecdRepository::class,
            \Inventario\Repository\ITkrechRepository::class => \Inventario\Repository\Impl\TkrechRepository::class,
            \Inventario\Repository\ITkvcnhRepository::class => \Inventario\Repository\Impl\TkvcnhRepository::class,
            \Inventario\Repository\ITkvpihRepository::class => \Inventario\Repository\Impl\TkvpihRepository::class,
            \Inventario\Repository\ITvartiRepository::class => \Inventario\Repository\Impl\TvartiRepository::class,
            \Inventario\Repository\ITvbodeRepository::class => \Inventario\Repository\Impl\TvbodeRepository::class,
            \Inventario\Repository\ITvdnarRepository::class => \Inventario\Repository\Impl\TvdnarRepository::class,
            \Inventario\Repository\ITvfacoRepository::class => \Inventario\Repository\Impl\TvfacoRepository::class,
            \Inventario\Repository\ITvmovdRepository::class => \Inventario\Repository\Impl\TvmovdRepository::class,
            \Inventario\Repository\ITvmovhRepository::class => \Inventario\Repository\Impl\TvmovhRepository::class,
            \Inventario\Repository\ITvmoviRepository::class => \Inventario\Repository\Impl\TvmoviRepository::class,
            \Inventario\Repository\ITvmovtRepository::class => \Inventario\Repository\Impl\TvmovtRepository::class,
            \Inventario\Repository\ITvpqadRepository::class => \Inventario\Repository\Impl\TvpqadRepository::class,
            \Inventario\Repository\ITvpqahRepository::class => \Inventario\Repository\Impl\TvpqahRepository::class,
            \Inventario\Repository\ITvsallRepository::class => \Inventario\Repository\Impl\TvsallRepository::class,
            \Inventario\Repository\ITvsalmRepository::class => \Inventario\Repository\Impl\TvsalmRepository::class,
            \Inventario\Repository\ITvsameRepository::class => \Inventario\Repository\Impl\TvsameRepository::class,
            \Inventario\Repository\ITvsamnRepository::class => \Inventario\Repository\Impl\TvsamnRepository::class,
            \Inventario\Repository\ITvsartRepository::class => \Inventario\Repository\Impl\TvsartRepository::class,
            \Inventario\Repository\ITvscalRepository::class => \Inventario\Repository\Impl\TvscalRepository::class,
            \Inventario\Repository\ITvscarRepository::class => \Inventario\Repository\Impl\TvscarRepository::class,
            \Inventario\Repository\ITvsendRepository::class => \Inventario\Repository\Impl\TvsendRepository::class,
            \Inventario\Repository\ITvtimbRepository::class => \Inventario\Repository\Impl\TvtimbRepository::class,
            ],
        'factories' => [
            \Inventario\Repository\Impl\TkrecdRepository::class => \Inventario\Repository\Factory\TkrecdRepositoryFactory::class,
            \Inventario\Repository\Impl\TkrechRepository::class => \Inventario\Repository\Factory\TkrechRepositoryFactory::class,
            \Inventario\Repository\Impl\TkvcnhRepository::class => \Inventario\Repository\Factory\TkvcnhRepositoryFactory::class,
            \Inventario\Repository\Impl\TkvpihRepository::class => \Inventario\Repository\Factory\TkvpihRepositoryFactory::class,
            \Inventario\Repository\Impl\TvartiRepository::class => \Inventario\Repository\Factory\TvartiRepositoryFactory::class,
            \Inventario\Repository\Impl\TvbodeRepository::class => \Inventario\Repository\Factory\TvbodeRepositoryFactory::class,
            \Inventario\Repository\Impl\TvdnarRepository::class => \Inventario\Repository\Factory\TvdnarRepositoryFactory::class,
            \Inventario\Repository\Impl\TvfacoRepository::class => \Inventario\Repository\Factory\TvfacoRepositoryFactory::class,
            \Inventario\Repository\Impl\TvmovdRepository::class => \Inventario\Repository\Factory\TvmovdRepositoryFactory::class,
            \Inventario\Repository\Impl\TvmovhRepository::class => \Inventario\Repository\Factory\TvmovhRepositoryFactory::class,
            \Inventario\Repository\Impl\TvmoviRepository::class => \Inventario\Repository\Factory\TvmoviRepositoryFactory::class,
            \Inventario\Repository\Impl\TvmovtRepository::class => \Inventario\Repository\Factory\TvmovtRepositoryFactory::class,
            \Inventario\Repository\Impl\TvpqadRepository::class => \Inventario\Repository\Factory\TvpqadRepositoryFactory::class,
            \Inventario\Repository\Impl\TvpqahRepository::class => \Inventario\Repository\Factory\TvpqahRepositoryFactory::class,
            \Inventario\Repository\Impl\TvsallRepository::class => \Inventario\Repository\Factory\TvsallRepositoryFactory::class,
            \Inventario\Repository\Impl\TvsalmRepository::class => \Inventario\Repository\Factory\TvsalmRepositoryFactory::class,
            \Inventario\Repository\Impl\TvsameRepository::class => \Inventario\Repository\Factory\TvsameRepositoryFactory::class,
            \Inventario\Repository\Impl\TvsamnRepository::class => \Inventario\Repository\Factory\TvsamnRepositoryFactory::class,
            \Inventario\Repository\Impl\TvsartRepository::class => \Inventario\Repository\Factory\TvsartRepositoryFactory::class,
            \Inventario\Repository\Impl\TvscalRepository::class => \Inventario\Repository\Factory\TvscalRepositoryFactory::class,
            \Inventario\Repository\Impl\TvscarRepository::class => \Inventario\Repository\Factory\TvscarRepositoryFactory::class,
            \Inventario\Repository\Impl\TvsendRepository::class => \Inventario\Repository\Factory\TvsendRepositoryFactory::class,
            \Inventario\Repository\Impl\TvtimbRepository::class => \Inventario\Repository\Factory\TvtimbRepositoryFactory::class,
            //Resource
            \Inventario\V1\Rest\Tkrecd\TkrecdResource::class => \Inventario\V1\Rest\Tkrecd\TkrecdResourceFactory::class,
            \Inventario\V1\Rest\Tkrech\TkrechResource::class => \Inventario\V1\Rest\Tkrech\TkrechResourceFactory::class,
            \Inventario\V1\Rest\Tkvcnh\TkvcnhResource::class => \Inventario\V1\Rest\Tkvcnh\TkvcnhResourceFactory::class,
            \Inventario\V1\Rest\Tkvpih\TkvpihResource::class => \Inventario\V1\Rest\Tkvpih\TkvpihResourceFactory::class,
            \Inventario\V1\Rest\Tvarti\TvartiResource::class => \Inventario\V1\Rest\Tvarti\TvartiResourceFactory::class,
            \Inventario\V1\Rest\Tvbode\TvbodeResource::class => \Inventario\V1\Rest\Tvbode\TvbodeResourceFactory::class,
            \Inventario\V1\Rest\Tvdnar\TvdnarResource::class => \Inventario\V1\Rest\Tvdnar\TvdnarResourceFactory::class,
            \Inventario\V1\Rest\Tvfaco\TvfacoResource::class => \Inventario\V1\Rest\Tvfaco\TvfacoResourceFactory::class,
            \Inventario\V1\Rest\Tvmovd\TvmovdResource::class => \Inventario\V1\Rest\Tvmovd\TvmovdResourceFactory::class,
            \Inventario\V1\Rest\Tvmovh\TvmovhResource::class => \Inventario\V1\Rest\Tvmovh\TvmovhResourceFactory::class,
            \Inventario\V1\Rest\Tvmovi\TvmoviResource::class => \Inventario\V1\Rest\Tvmovi\TvmoviResourceFactory::class,
            \Inventario\V1\Rest\Tvmovt\TvmovtResource::class => \Inventario\V1\Rest\Tvmovt\TvmovtResourceFactory::class,
            \Inventario\V1\Rest\Tvpqad\TvpqadResource::class => \Inventario\V1\Rest\Tvpqad\TvpqadResourceFactory::class,
            \Inventario\V1\Rest\Tvpqah\TvpqahResource::class => \Inventario\V1\Rest\Tvpqah\TvpqahResourceFactory::class,
            \Inventario\V1\Rest\Tvsall\TvsallResource::class => \Inventario\V1\Rest\Tvsall\TvsallResourceFactory::class,
            \Inventario\V1\Rest\Tvsalm\TvsalmResource::class => \Inventario\V1\Rest\Tvsalm\TvsalmResourceFactory::class,
            \Inventario\V1\Rest\Tvsame\TvsameResource::class => \Inventario\V1\Rest\Tvsame\TvsameResourceFactory::class,
            \Inventario\V1\Rest\Tvsamn\TvsamnResource::class => \Inventario\V1\Rest\Tvsamn\TvsamnResourceFactory::class,
            \Inventario\V1\Rest\Tvsart\TvsartResource::class => \Inventario\V1\Rest\Tvsart\TvsartResourceFactory::class,
            \Inventario\V1\Rest\Tvscal\TvscalResource::class => \Inventario\V1\Rest\Tvscal\TvscalResourceFactory::class,
            \Inventario\V1\Rest\Tvscar\TvscarResource::class => \Inventario\V1\Rest\Tvscar\TvscarResourceFactory::class,
            \Inventario\V1\Rest\Tvsend\TvsendResource::class => \Inventario\V1\Rest\Tvsend\TvsendResourceFactory::class,
            \Inventario\V1\Rest\Tvtimb\TvtimbResource::class => \Inventario\V1\Rest\Tvtimb\TvtimbResourceFactory::class,
        ],
    ],
    'router' => [
        'routes' => [
            'inventario.rest.tkrecd' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tkrecd[/:tkrecd_id]',
                    'defaults' => [
                        'controller' => 'Inventario\\V1\\Rest\\Tkrecd\\Controller',
                    ],
                ],
            ],
            'inventario.rest.tkrech' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tkrech[/:tkrech_id]',
                    'defaults' => [
                        'controller' => 'Inventario\\V1\\Rest\\Tkrech\\Controller',
                    ],
                ],
            ],
            'inventario.rest.tkvcnh' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tkvcnh[/:tkvcnh_id]',
                    'defaults' => [
                        'controller' => 'Inventario\\V1\\Rest\\Tkvcnh\\Controller',
                    ],
                ],
            ],
            'inventario.rest.tkvpih' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tkvpih[/:tkvpih_id]',
                    'defaults' => [
                        'controller' => 'Inventario\\V1\\Rest\\Tkvpih\\Controller',
                    ],
                ],
            ],
            'inventario.rest.tvarti' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tvarti[/:tvarti_id]',
                    'defaults' => [
                        'controller' => 'Inventario\\V1\\Rest\\Tvarti\\Controller',
                    ],
                ],
            ],
            'inventario.rest.tvbode' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tvbode[/:tvbode_id]',
                    'defaults' => [
                        'controller' => 'Inventario\\V1\\Rest\\Tvbode\\Controller',
                    ],
                ],
            ],
            'inventario.rest.tvdnar' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tvdnar[/:tvdnar_id]',
                    'defaults' => [
                        'controller' => 'Inventario\\V1\\Rest\\Tvdnar\\Controller',
                    ],
                ],
            ],
            'inventario.rest.tvfaco' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tvfaco[/:tvfaco_id]',
                    'defaults' => [
                        'controller' => 'Inventario\\V1\\Rest\\Tvfaco\\Controller',
                    ],
                ],
            ],
            'inventario.rest.tvmovd' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tvmovd[/:tvmovd_id]',
                    'defaults' => [
                        'controller' => 'Inventario\\V1\\Rest\\Tvmovd\\Controller',
                    ],
                ],
            ],
            'inventario.rest.tvmovh' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tvmovh[/:tvmovh_id]',
                    'defaults' => [
                        'controller' => 'Inventario\\V1\\Rest\\Tvmovh\\Controller',
                    ],
                ],
            ],
            'inventario.rest.tvmovi' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tvmovi[/:tvmovi_id]',
                    'defaults' => [
                        'controller' => 'Inventario\\V1\\Rest\\Tvmovi\\Controller',
                    ],
                ],
            ],
            'inventario.rest.tvmovt' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tvmovt[/:tvmovt_id]',
                    'defaults' => [
                        'controller' => 'Inventario\\V1\\Rest\\Tvmovt\\Controller',
                    ],
                ],
            ],
            'inventario.rest.tvpqad' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tvpqad[/:tvpqad_id]',
                    'defaults' => [
                        'controller' => 'Inventario\\V1\\Rest\\Tvpqad\\Controller',
                    ],
                ],
            ],
            'inventario.rest.tvpqah' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tvpqah[/:tvpqah_id]',
                    'defaults' => [
                        'controller' => 'Inventario\\V1\\Rest\\Tvpqah\\Controller',
                    ],
                ],
            ],
            'inventario.rest.tvsall' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tvsall[/:tvsall_id]',
                    'defaults' => [
                        'controller' => 'Inventario\\V1\\Rest\\Tvsall\\Controller',
                    ],
                ],
            ],
            'inventario.rest.tvsalm' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tvsalm[/:tvsalm_id]',
                    'defaults' => [
                        'controller' => 'Inventario\\V1\\Rest\\Tvsalm\\Controller',
                    ],
                ],
            ],
            'inventario.rest.tvsame' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tvsame[/:tvsame_id]',
                    'defaults' => [
                        'controller' => 'Inventario\\V1\\Rest\\Tvsame\\Controller',
                    ],
                ],
            ],
            'inventario.rest.tvsamn' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tvsamn[/:tvsamn_id]',
                    'defaults' => [
                        'controller' => 'Inventario\\V1\\Rest\\Tvsamn\\Controller',
                    ],
                ],
            ],
            'inventario.rest.tvsart' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tvsart[/:tvsart_id]',
                    'defaults' => [
                        'controller' => 'Inventario\\V1\\Rest\\Tvsart\\Controller',
                    ],
                ],
            ],
            'inventario.rest.tvscal' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tvscal[/:tvscal_id]',
                    'defaults' => [
                        'controller' => 'Inventario\\V1\\Rest\\Tvscal\\Controller',
                    ],
                ],
            ],
            'inventario.rest.tvscar' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tvscar[/:tvscar_id]',
                    'defaults' => [
                        'controller' => 'Inventario\\V1\\Rest\\Tvscar\\Controller',
                    ],
                ],
            ],
            'inventario.rest.tvsend' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tvsend[/:tvsend_id]',
                    'defaults' => [
                        'controller' => 'Inventario\\V1\\Rest\\Tvsend\\Controller',
                    ],
                ],
            ],
            'inventario.rest.tvtimb' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/tvtimb[/:tvtimb_id]',
                    'defaults' => [
                        'controller' => 'Inventario\\V1\\Rest\\Tvtimb\\Controller',
                    ],
                ],
            ],
        ],
    ],
    'zf-versioning' => [
        'uri' => [
            0 => 'inventario.rest.tkrecd',
            1 => 'inventario.rest.tkrech',
            2 => 'inventario.rest.tkvcnh',
            3 => 'inventario.rest.tkvpih',
            4 => 'inventario.rest.tvarti',
            5 => 'inventario.rest.tvbode',
            6 => 'inventario.rest.tvdnar',
            7 => 'inventario.rest.tvfaco',
            8 => 'inventario.rest.tvmovd',
            9 => 'inventario.rest.tvmovh',
            10 => 'inventario.rest.tvmovi',
            11 => 'inventario.rest.tvmovt',
            12 => 'inventario.rest.tvpqad',
            13 => 'inventario.rest.tvpqah',
            14 => 'inventario.rest.tvsall',
            15 => 'inventario.rest.tvsalm',
            16 => 'inventario.rest.tvsame',
            17 => 'inventario.rest.tvsamn',
            18 => 'inventario.rest.tvsart',
            19 => 'inventario.rest.tvscal',
            20 => 'inventario.rest.tvscar',
            21 => 'inventario.rest.tvsend',
            22 => 'inventario.rest.tvtimb',
        ],
    ],
    'zf-rest' => [
        'Inventario\\V1\\Rest\\Tkrecd\\Controller' => [
            'listener' => \Inventario\V1\Rest\Tkrecd\TkrecdResource::class,
            'route_name' => 'inventario.rest.tkrecd',
            'route_identifier_name' => 'tkrecd_id',
            'collection_name' => 'tkrecd',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Inventario\V1\Rest\Tkrecd\TkrecdEntity::class,
            'collection_class' => \Inventario\V1\Rest\Tkrecd\TkrecdCollection::class,
            'service_name' => 'Tkrecd',
        ],
        'Inventario\\V1\\Rest\\Tkrech\\Controller' => [
            'listener' => \Inventario\V1\Rest\Tkrech\TkrechResource::class,
            'route_name' => 'inventario.rest.tkrech',
            'route_identifier_name' => 'tkrech_id',
            'collection_name' => 'tkrech',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Inventario\V1\Rest\Tkrech\TkrechEntity::class,
            'collection_class' => \Inventario\V1\Rest\Tkrech\TkrechCollection::class,
            'service_name' => 'Tkrech',
        ],
        'Inventario\\V1\\Rest\\Tkvcnh\\Controller' => [
            'listener' => \Inventario\V1\Rest\Tkvcnh\TkvcnhResource::class,
            'route_name' => 'inventario.rest.tkvcnh',
            'route_identifier_name' => 'tkvcnh_id',
            'collection_name' => 'tkvcnh',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Inventario\V1\Rest\Tkvcnh\TkvcnhEntity::class,
            'collection_class' => \Inventario\V1\Rest\Tkvcnh\TkvcnhCollection::class,
            'service_name' => 'Tkvcnh',
        ],
        'Inventario\\V1\\Rest\\Tkvpih\\Controller' => [
            'listener' => \Inventario\V1\Rest\Tkvpih\TkvpihResource::class,
            'route_name' => 'inventario.rest.tkvpih',
            'route_identifier_name' => 'tkvpih_id',
            'collection_name' => 'tkvpih',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Inventario\V1\Rest\Tkvpih\TkvpihEntity::class,
            'collection_class' => \Inventario\V1\Rest\Tkvpih\TkvpihCollection::class,
            'service_name' => 'Tkvpih',
        ],
        'Inventario\\V1\\Rest\\Tvarti\\Controller' => [
            'listener' => \Inventario\V1\Rest\Tvarti\TvartiResource::class,
            'route_name' => 'inventario.rest.tvarti',
            'route_identifier_name' => 'tvarti_id',
            'collection_name' => 'tvarti',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Inventario\V1\Rest\Tvarti\TvartiEntity::class,
            'collection_class' => \Inventario\V1\Rest\Tvarti\TvartiCollection::class,
            'service_name' => 'Tvarti',
        ],
        'Inventario\\V1\\Rest\\Tvbode\\Controller' => [
            'listener' => \Inventario\V1\Rest\Tvbode\TvbodeResource::class,
            'route_name' => 'inventario.rest.tvbode',
            'route_identifier_name' => 'tvbode_id',
            'collection_name' => 'tvbode',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Inventario\V1\Rest\Tvbode\TvbodeEntity::class,
            'collection_class' => \Inventario\V1\Rest\Tvbode\TvbodeCollection::class,
            'service_name' => 'Tvbode',
        ],
        'Inventario\\V1\\Rest\\Tvdnar\\Controller' => [
            'listener' => \Inventario\V1\Rest\Tvdnar\TvdnarResource::class,
            'route_name' => 'inventario.rest.tvdnar',
            'route_identifier_name' => 'tvdnar_id',
            'collection_name' => 'tvdnar',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Inventario\V1\Rest\Tvdnar\TvdnarEntity::class,
            'collection_class' => \Inventario\V1\Rest\Tvdnar\TvdnarCollection::class,
            'service_name' => 'Tvdnar',
        ],
        'Inventario\\V1\\Rest\\Tvfaco\\Controller' => [
            'listener' => \Inventario\V1\Rest\Tvfaco\TvfacoResource::class,
            'route_name' => 'inventario.rest.tvfaco',
            'route_identifier_name' => 'tvfaco_id',
            'collection_name' => 'tvfaco',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Inventario\V1\Rest\Tvfaco\TvfacoEntity::class,
            'collection_class' => \Inventario\V1\Rest\Tvfaco\TvfacoCollection::class,
            'service_name' => 'Tvfaco',
        ],
        'Inventario\\V1\\Rest\\Tvmovd\\Controller' => [
            'listener' => \Inventario\V1\Rest\Tvmovd\TvmovdResource::class,
            'route_name' => 'inventario.rest.tvmovd',
            'route_identifier_name' => 'tvmovd_id',
            'collection_name' => 'tvmovd',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Inventario\V1\Rest\Tvmovd\TvmovdEntity::class,
            'collection_class' => \Inventario\V1\Rest\Tvmovd\TvmovdCollection::class,
            'service_name' => 'Tvmovd',
        ],
        'Inventario\\V1\\Rest\\Tvmovh\\Controller' => [
            'listener' => \Inventario\V1\Rest\Tvmovh\TvmovhResource::class,
            'route_name' => 'inventario.rest.tvmovh',
            'route_identifier_name' => 'tvmovh_id',
            'collection_name' => 'tvmovh',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Inventario\V1\Rest\Tvmovh\TvmovhEntity::class,
            'collection_class' => \Inventario\V1\Rest\Tvmovh\TvmovhCollection::class,
            'service_name' => 'Tvmovh',
        ],
        'Inventario\\V1\\Rest\\Tvmovi\\Controller' => [
            'listener' => \Inventario\V1\Rest\Tvmovi\TvmoviResource::class,
            'route_name' => 'inventario.rest.tvmovi',
            'route_identifier_name' => 'tvmovi_id',
            'collection_name' => 'tvmovi',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Inventario\V1\Rest\Tvmovi\TvmoviEntity::class,
            'collection_class' => \Inventario\V1\Rest\Tvmovi\TvmoviCollection::class,
            'service_name' => 'Tvmovi',
        ],
        'Inventario\\V1\\Rest\\Tvmovt\\Controller' => [
            'listener' => \Inventario\V1\Rest\Tvmovt\TvmovtResource::class,
            'route_name' => 'inventario.rest.tvmovt',
            'route_identifier_name' => 'tvmovt_id',
            'collection_name' => 'tvmovt',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Inventario\V1\Rest\Tvmovt\TvmovtEntity::class,
            'collection_class' => \Inventario\V1\Rest\Tvmovt\TvmovtCollection::class,
            'service_name' => 'Tvmovt',
        ],
        'Inventario\\V1\\Rest\\Tvpqad\\Controller' => [
            'listener' => \Inventario\V1\Rest\Tvpqad\TvpqadResource::class,
            'route_name' => 'inventario.rest.tvpqad',
            'route_identifier_name' => 'tvpqad_id',
            'collection_name' => 'tvpqad',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Inventario\V1\Rest\Tvpqad\TvpqadEntity::class,
            'collection_class' => \Inventario\V1\Rest\Tvpqad\TvpqadCollection::class,
            'service_name' => 'Tvpqad',
        ],
        'Inventario\\V1\\Rest\\Tvpqah\\Controller' => [
            'listener' => \Inventario\V1\Rest\Tvpqah\TvpqahResource::class,
            'route_name' => 'inventario.rest.tvpqah',
            'route_identifier_name' => 'tvpqah_id',
            'collection_name' => 'tvpqah',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Inventario\V1\Rest\Tvpqah\TvpqahEntity::class,
            'collection_class' => \Inventario\V1\Rest\Tvpqah\TvpqahCollection::class,
            'service_name' => 'Tvpqah',
        ],
        'Inventario\\V1\\Rest\\Tvsall\\Controller' => [
            'listener' => \Inventario\V1\Rest\Tvsall\TvsallResource::class,
            'route_name' => 'inventario.rest.tvsall',
            'route_identifier_name' => 'tvsall_id',
            'collection_name' => 'tvsall',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Inventario\V1\Rest\Tvsall\TvsallEntity::class,
            'collection_class' => \Inventario\V1\Rest\Tvsall\TvsallCollection::class,
            'service_name' => 'Tvsall',
        ],
        'Inventario\\V1\\Rest\\Tvsalm\\Controller' => [
            'listener' => \Inventario\V1\Rest\Tvsalm\TvsalmResource::class,
            'route_name' => 'inventario.rest.tvsalm',
            'route_identifier_name' => 'tvsalm_id',
            'collection_name' => 'tvsalm',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Inventario\V1\Rest\Tvsalm\TvsalmEntity::class,
            'collection_class' => \Inventario\V1\Rest\Tvsalm\TvsalmCollection::class,
            'service_name' => 'Tvsalm',
        ],
        'Inventario\\V1\\Rest\\Tvsame\\Controller' => [
            'listener' => \Inventario\V1\Rest\Tvsame\TvsameResource::class,
            'route_name' => 'inventario.rest.tvsame',
            'route_identifier_name' => 'tvsame_id',
            'collection_name' => 'tvsame',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Inventario\V1\Rest\Tvsame\TvsameEntity::class,
            'collection_class' => \Inventario\V1\Rest\Tvsame\TvsameCollection::class,
            'service_name' => 'Tvsame',
        ],
        'Inventario\\V1\\Rest\\Tvsamn\\Controller' => [
            'listener' => \Inventario\V1\Rest\Tvsamn\TvsamnResource::class,
            'route_name' => 'inventario.rest.tvsamn',
            'route_identifier_name' => 'tvsamn_id',
            'collection_name' => 'tvsamn',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Inventario\V1\Rest\Tvsamn\TvsamnEntity::class,
            'collection_class' => \Inventario\V1\Rest\Tvsamn\TvsamnCollection::class,
            'service_name' => 'Tvsamn',
        ],
        'Inventario\\V1\\Rest\\Tvsart\\Controller' => [
            'listener' => \Inventario\V1\Rest\Tvsart\TvsartResource::class,
            'route_name' => 'inventario.rest.tvsart',
            'route_identifier_name' => 'tvsart_id',
            'collection_name' => 'tvsart',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Inventario\V1\Rest\Tvsart\TvsartEntity::class,
            'collection_class' => \Inventario\V1\Rest\Tvsart\TvsartCollection::class,
            'service_name' => 'Tvsart',
        ],
        'Inventario\\V1\\Rest\\Tvscal\\Controller' => [
            'listener' => \Inventario\V1\Rest\Tvscal\TvscalResource::class,
            'route_name' => 'inventario.rest.tvscal',
            'route_identifier_name' => 'tvscal_id',
            'collection_name' => 'tvscal',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Inventario\V1\Rest\Tvscal\TvscalEntity::class,
            'collection_class' => \Inventario\V1\Rest\Tvscal\TvscalCollection::class,
            'service_name' => 'Tvscal',
        ],
        'Inventario\\V1\\Rest\\Tvscar\\Controller' => [
            'listener' => \Inventario\V1\Rest\Tvscar\TvscarResource::class,
            'route_name' => 'inventario.rest.tvscar',
            'route_identifier_name' => 'tvscar_id',
            'collection_name' => 'tvscar',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Inventario\V1\Rest\Tvscar\TvscarEntity::class,
            'collection_class' => \Inventario\V1\Rest\Tvscar\TvscarCollection::class,
            'service_name' => 'Tvscar',
        ],
        'Inventario\\V1\\Rest\\Tvsend\\Controller' => [
            'listener' => \Inventario\V1\Rest\Tvsend\TvsendResource::class,
            'route_name' => 'inventario.rest.tvsend',
            'route_identifier_name' => 'tvsend_id',
            'collection_name' => 'tvsend',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Inventario\V1\Rest\Tvsend\TvsendEntity::class,
            'collection_class' => \Inventario\V1\Rest\Tvsend\TvsendCollection::class,
            'service_name' => 'Tvsend',
        ],
        'Inventario\\V1\\Rest\\Tvtimb\\Controller' => [
            'listener' => \Inventario\V1\Rest\Tvtimb\TvtimbResource::class,
            'route_name' => 'inventario.rest.tvtimb',
            'route_identifier_name' => 'tvtimb_id',
            'collection_name' => 'tvtimb',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \Inventario\V1\Rest\Tvtimb\TvtimbEntity::class,
            'collection_class' => \Inventario\V1\Rest\Tvtimb\TvtimbCollection::class,
            'service_name' => 'Tvtimb',
        ],
    ],
    'zf-content-negotiation' => [
        'controllers' => [
            'Inventario\\V1\\Rest\\Tkrecd\\Controller' => 'HalJson',
            'Inventario\\V1\\Rest\\Tkrech\\Controller' => 'HalJson',
            'Inventario\\V1\\Rest\\Tkvcnh\\Controller' => 'HalJson',
            'Inventario\\V1\\Rest\\Tkvpih\\Controller' => 'HalJson',
            'Inventario\\V1\\Rest\\Tvarti\\Controller' => 'HalJson',
            'Inventario\\V1\\Rest\\Tvbode\\Controller' => 'HalJson',
            'Inventario\\V1\\Rest\\Tvdnar\\Controller' => 'HalJson',
            'Inventario\\V1\\Rest\\Tvfaco\\Controller' => 'HalJson',
            'Inventario\\V1\\Rest\\Tvmovd\\Controller' => 'HalJson',
            'Inventario\\V1\\Rest\\Tvmovh\\Controller' => 'HalJson',
            'Inventario\\V1\\Rest\\Tvmovi\\Controller' => 'HalJson',
            'Inventario\\V1\\Rest\\Tvmovt\\Controller' => 'HalJson',
            'Inventario\\V1\\Rest\\Tvpqad\\Controller' => 'HalJson',
            'Inventario\\V1\\Rest\\Tvpqah\\Controller' => 'HalJson',
            'Inventario\\V1\\Rest\\Tvsall\\Controller' => 'HalJson',
            'Inventario\\V1\\Rest\\Tvsalm\\Controller' => 'HalJson',
            'Inventario\\V1\\Rest\\Tvsame\\Controller' => 'HalJson',
            'Inventario\\V1\\Rest\\Tvsamn\\Controller' => 'HalJson',
            'Inventario\\V1\\Rest\\Tvsart\\Controller' => 'HalJson',
            'Inventario\\V1\\Rest\\Tvscal\\Controller' => 'HalJson',
            'Inventario\\V1\\Rest\\Tvscar\\Controller' => 'HalJson',
            'Inventario\\V1\\Rest\\Tvsend\\Controller' => 'HalJson',
            'Inventario\\V1\\Rest\\Tvtimb\\Controller' => 'HalJson',
        ],
        'accept_whitelist' => [
            'Inventario\\V1\\Rest\\Tkrecd\\Controller' => [
                0 => 'application/vnd.inventario.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Inventario\\V1\\Rest\\Tkrech\\Controller' => [
                0 => 'application/vnd.inventario.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Inventario\\V1\\Rest\\Tkvcnh\\Controller' => [
                0 => 'application/vnd.inventario.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Inventario\\V1\\Rest\\Tkvpih\\Controller' => [
                0 => 'application/vnd.inventario.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Inventario\\V1\\Rest\\Tvarti\\Controller' => [
                0 => 'application/vnd.inventario.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Inventario\\V1\\Rest\\Tvbode\\Controller' => [
                0 => 'application/vnd.inventario.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Inventario\\V1\\Rest\\Tvdnar\\Controller' => [
                0 => 'application/vnd.inventario.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Inventario\\V1\\Rest\\Tvfaco\\Controller' => [
                0 => 'application/vnd.inventario.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Inventario\\V1\\Rest\\Tvmovd\\Controller' => [
                0 => 'application/vnd.inventario.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Inventario\\V1\\Rest\\Tvmovh\\Controller' => [
                0 => 'application/vnd.inventario.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Inventario\\V1\\Rest\\Tvmovi\\Controller' => [
                0 => 'application/vnd.inventario.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Inventario\\V1\\Rest\\Tvmovt\\Controller' => [
                0 => 'application/vnd.inventario.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Inventario\\V1\\Rest\\Tvpqad\\Controller' => [
                0 => 'application/vnd.inventario.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Inventario\\V1\\Rest\\Tvpqah\\Controller' => [
                0 => 'application/vnd.inventario.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Inventario\\V1\\Rest\\Tvsall\\Controller' => [
                0 => 'application/vnd.inventario.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Inventario\\V1\\Rest\\Tvsalm\\Controller' => [
                0 => 'application/vnd.inventario.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Inventario\\V1\\Rest\\Tvsame\\Controller' => [
                0 => 'application/vnd.inventario.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Inventario\\V1\\Rest\\Tvsamn\\Controller' => [
                0 => 'application/vnd.inventario.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Inventario\\V1\\Rest\\Tvsart\\Controller' => [
                0 => 'application/vnd.inventario.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Inventario\\V1\\Rest\\Tvscal\\Controller' => [
                0 => 'application/vnd.inventario.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Inventario\\V1\\Rest\\Tvscar\\Controller' => [
                0 => 'application/vnd.inventario.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Inventario\\V1\\Rest\\Tvsend\\Controller' => [
                0 => 'application/vnd.inventario.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'Inventario\\V1\\Rest\\Tvtimb\\Controller' => [
                0 => 'application/vnd.inventario.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
        ],
        'content_type_whitelist' => [
            'Inventario\\V1\\Rest\\Tkrecd\\Controller' => [
                0 => 'application/vnd.inventario.v1+json',
                1 => 'application/json',
            ],
            'Inventario\\V1\\Rest\\Tkrech\\Controller' => [
                0 => 'application/vnd.inventario.v1+json',
                1 => 'application/json',
            ],
            'Inventario\\V1\\Rest\\Tkvcnh\\Controller' => [
                0 => 'application/vnd.inventario.v1+json',
                1 => 'application/json',
            ],
            'Inventario\\V1\\Rest\\Tkvpih\\Controller' => [
                0 => 'application/vnd.inventario.v1+json',
                1 => 'application/json',
            ],
            'Inventario\\V1\\Rest\\Tvarti\\Controller' => [
                0 => 'application/vnd.inventario.v1+json',
                1 => 'application/json',
            ],
            'Inventario\\V1\\Rest\\Tvbode\\Controller' => [
                0 => 'application/vnd.inventario.v1+json',
                1 => 'application/json',
            ],
            'Inventario\\V1\\Rest\\Tvdnar\\Controller' => [
                0 => 'application/vnd.inventario.v1+json',
                1 => 'application/json',
            ],
            'Inventario\\V1\\Rest\\Tvfaco\\Controller' => [
                0 => 'application/vnd.inventario.v1+json',
                1 => 'application/json',
            ],
            'Inventario\\V1\\Rest\\Tvmovd\\Controller' => [
                0 => 'application/vnd.inventario.v1+json',
                1 => 'application/json',
            ],
            'Inventario\\V1\\Rest\\Tvmovh\\Controller' => [
                0 => 'application/vnd.inventario.v1+json',
                1 => 'application/json',
            ],
            'Inventario\\V1\\Rest\\Tvmovi\\Controller' => [
                0 => 'application/vnd.inventario.v1+json',
                1 => 'application/json',
            ],
            'Inventario\\V1\\Rest\\Tvmovt\\Controller' => [
                0 => 'application/vnd.inventario.v1+json',
                1 => 'application/json',
            ],
            'Inventario\\V1\\Rest\\Tvpqad\\Controller' => [
                0 => 'application/vnd.inventario.v1+json',
                1 => 'application/json',
            ],
            'Inventario\\V1\\Rest\\Tvpqah\\Controller' => [
                0 => 'application/vnd.inventario.v1+json',
                1 => 'application/json',
            ],
            'Inventario\\V1\\Rest\\Tvsall\\Controller' => [
                0 => 'application/vnd.inventario.v1+json',
                1 => 'application/json',
            ],
            'Inventario\\V1\\Rest\\Tvsalm\\Controller' => [
                0 => 'application/vnd.inventario.v1+json',
                1 => 'application/json',
            ],
            'Inventario\\V1\\Rest\\Tvsame\\Controller' => [
                0 => 'application/vnd.inventario.v1+json',
                1 => 'application/json',
            ],
            'Inventario\\V1\\Rest\\Tvsamn\\Controller' => [
                0 => 'application/vnd.inventario.v1+json',
                1 => 'application/json',
            ],
            'Inventario\\V1\\Rest\\Tvsart\\Controller' => [
                0 => 'application/vnd.inventario.v1+json',
                1 => 'application/json',
            ],
            'Inventario\\V1\\Rest\\Tvscal\\Controller' => [
                0 => 'application/vnd.inventario.v1+json',
                1 => 'application/json',
            ],
            'Inventario\\V1\\Rest\\Tvscar\\Controller' => [
                0 => 'application/vnd.inventario.v1+json',
                1 => 'application/json',
            ],
            'Inventario\\V1\\Rest\\Tvsend\\Controller' => [
                0 => 'application/vnd.inventario.v1+json',
                1 => 'application/json',
            ],
            'Inventario\\V1\\Rest\\Tvtimb\\Controller' => [
                0 => 'application/vnd.inventario.v1+json',
                1 => 'application/json',
            ],
        ],
    ],
    'zf-hal' => [
        'metadata_map' => [
            \Inventario\V1\Rest\Tkrecd\TkrecdEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'inventario.rest.tkrecd',
                'route_identifier_name' => 'tkrecd_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Inventario\V1\Rest\Tkrecd\TkrecdCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'inventario.rest.tkrecd',
                'route_identifier_name' => 'tkrecd_id',
                'is_collection' => true,
            ],
            \Inventario\V1\Rest\Tkrech\TkrechEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'inventario.rest.tkrech',
                'route_identifier_name' => 'tkrech_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Inventario\V1\Rest\Tkrech\TkrechCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'inventario.rest.tkrech',
                'route_identifier_name' => 'tkrech_id',
                'is_collection' => true,
            ],
            \Inventario\V1\Rest\Tkvcnh\TkvcnhEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'inventario.rest.tkvcnh',
                'route_identifier_name' => 'tkvcnh_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Inventario\V1\Rest\Tkvcnh\TkvcnhCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'inventario.rest.tkvcnh',
                'route_identifier_name' => 'tkvcnh_id',
                'is_collection' => true,
            ],
            \Inventario\V1\Rest\Tkvpih\TkvpihEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'inventario.rest.tkvpih',
                'route_identifier_name' => 'tkvpih_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Inventario\V1\Rest\Tkvpih\TkvpihCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'inventario.rest.tkvpih',
                'route_identifier_name' => 'tkvpih_id',
                'is_collection' => true,
            ],
            \Inventario\V1\Rest\Tvarti\TvartiEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'inventario.rest.tvarti',
                'route_identifier_name' => 'tvarti_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Inventario\V1\Rest\Tvarti\TvartiCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'inventario.rest.tvarti',
                'route_identifier_name' => 'tvarti_id',
                'is_collection' => true,
            ],
            \Inventario\V1\Rest\Tvbode\TvbodeEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'inventario.rest.tvbode',
                'route_identifier_name' => 'tvbode_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Inventario\V1\Rest\Tvbode\TvbodeCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'inventario.rest.tvbode',
                'route_identifier_name' => 'tvbode_id',
                'is_collection' => true,
            ],
            \Inventario\V1\Rest\Tvdnar\TvdnarEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'inventario.rest.tvdnar',
                'route_identifier_name' => 'tvdnar_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Inventario\V1\Rest\Tvdnar\TvdnarCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'inventario.rest.tvdnar',
                'route_identifier_name' => 'tvdnar_id',
                'is_collection' => true,
            ],
            \Inventario\V1\Rest\Tvfaco\TvfacoEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'inventario.rest.tvfaco',
                'route_identifier_name' => 'tvfaco_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Inventario\V1\Rest\Tvfaco\TvfacoCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'inventario.rest.tvfaco',
                'route_identifier_name' => 'tvfaco_id',
                'is_collection' => true,
            ],
            \Inventario\V1\Rest\Tvmovd\TvmovdEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'inventario.rest.tvmovd',
                'route_identifier_name' => 'tvmovd_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Inventario\V1\Rest\Tvmovd\TvmovdCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'inventario.rest.tvmovd',
                'route_identifier_name' => 'tvmovd_id',
                'is_collection' => true,
            ],
            \Inventario\V1\Rest\Tvmovh\TvmovhEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'inventario.rest.tvmovh',
                'route_identifier_name' => 'tvmovh_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Inventario\V1\Rest\Tvmovh\TvmovhCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'inventario.rest.tvmovh',
                'route_identifier_name' => 'tvmovh_id',
                'is_collection' => true,
            ],
            \Inventario\V1\Rest\Tvmovi\TvmoviEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'inventario.rest.tvmovi',
                'route_identifier_name' => 'tvmovi_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Inventario\V1\Rest\Tvmovi\TvmoviCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'inventario.rest.tvmovi',
                'route_identifier_name' => 'tvmovi_id',
                'is_collection' => true,
            ],
            \Inventario\V1\Rest\Tvmovt\TvmovtEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'inventario.rest.tvmovt',
                'route_identifier_name' => 'tvmovt_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Inventario\V1\Rest\Tvmovt\TvmovtCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'inventario.rest.tvmovt',
                'route_identifier_name' => 'tvmovt_id',
                'is_collection' => true,
            ],
            \Inventario\V1\Rest\Tvpqad\TvpqadEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'inventario.rest.tvpqad',
                'route_identifier_name' => 'tvpqad_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Inventario\V1\Rest\Tvpqad\TvpqadCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'inventario.rest.tvpqad',
                'route_identifier_name' => 'tvpqad_id',
                'is_collection' => true,
            ],
            \Inventario\V1\Rest\Tvpqah\TvpqahEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'inventario.rest.tvpqah',
                'route_identifier_name' => 'tvpqah_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Inventario\V1\Rest\Tvpqah\TvpqahCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'inventario.rest.tvpqah',
                'route_identifier_name' => 'tvpqah_id',
                'is_collection' => true,
            ],
            \Inventario\V1\Rest\Tvsall\TvsallEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'inventario.rest.tvsall',
                'route_identifier_name' => 'tvsall_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Inventario\V1\Rest\Tvsall\TvsallCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'inventario.rest.tvsall',
                'route_identifier_name' => 'tvsall_id',
                'is_collection' => true,
            ],
            \Inventario\V1\Rest\Tvsalm\TvsalmEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'inventario.rest.tvsalm',
                'route_identifier_name' => 'tvsalm_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Inventario\V1\Rest\Tvsalm\TvsalmCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'inventario.rest.tvsalm',
                'route_identifier_name' => 'tvsalm_id',
                'is_collection' => true,
            ],
            \Inventario\V1\Rest\Tvsame\TvsameEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'inventario.rest.tvsame',
                'route_identifier_name' => 'tvsame_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Inventario\V1\Rest\Tvsame\TvsameCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'inventario.rest.tvsame',
                'route_identifier_name' => 'tvsame_id',
                'is_collection' => true,
            ],
            \Inventario\V1\Rest\Tvsamn\TvsamnEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'inventario.rest.tvsamn',
                'route_identifier_name' => 'tvsamn_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Inventario\V1\Rest\Tvsamn\TvsamnCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'inventario.rest.tvsamn',
                'route_identifier_name' => 'tvsamn_id',
                'is_collection' => true,
            ],
            \Inventario\V1\Rest\Tvsart\TvsartEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'inventario.rest.tvsart',
                'route_identifier_name' => 'tvsart_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Inventario\V1\Rest\Tvsart\TvsartCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'inventario.rest.tvsart',
                'route_identifier_name' => 'tvsart_id',
                'is_collection' => true,
            ],
            \Inventario\V1\Rest\Tvscal\TvscalEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'inventario.rest.tvscal',
                'route_identifier_name' => 'tvscal_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Inventario\V1\Rest\Tvscal\TvscalCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'inventario.rest.tvscal',
                'route_identifier_name' => 'tvscal_id',
                'is_collection' => true,
            ],
            \Inventario\V1\Rest\Tvscar\TvscarEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'inventario.rest.tvscar',
                'route_identifier_name' => 'tvscar_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Inventario\V1\Rest\Tvscar\TvscarCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'inventario.rest.tvscar',
                'route_identifier_name' => 'tvscar_id',
                'is_collection' => true,
            ],
            \Inventario\V1\Rest\Tvsend\TvsendEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'inventario.rest.tvsend',
                'route_identifier_name' => 'tvsend_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Inventario\V1\Rest\Tvsend\TvsendCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'inventario.rest.tvsend',
                'route_identifier_name' => 'tvsend_id',
                'is_collection' => true,
            ],
            \Inventario\V1\Rest\Tvtimb\TvtimbEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'inventario.rest.tvtimb',
                'route_identifier_name' => 'tvtimb_id',
                'hydrator' => \Zend\Hydrator\ArraySerializable::class,
            ],
            \Inventario\V1\Rest\Tvtimb\TvtimbCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'inventario.rest.tvtimb',
                'route_identifier_name' => 'tvtimb_id',
                'is_collection' => true,
            ],
        ],
    ],
];
